### ISSUE TITLE
Add a nice FAVICON to the website

### ISSUE THREAD

**Issue by SurajPratap10** [SurajPratap10/Imagine_AI#10]
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/6143b8f0-7228-49b3-abff-f0ce15946fde)

**Comment by mani200307** [comment]
Can I work on this issue? Could you please assign me this?

**Comment by SurajPratap10** [comment]
> @SurajPratap10, Can I work on this issue? Could you please assign me this?

Assigning it to you @mani200307 📌

**Comment by SurajPratap10** [comment]
@mani200307  You can improve the favicon to a better version that resembles the `AI` thing

**Comment by mani200307** [comment]
Sure, I'll show you the favicon logo, Once its ready.

**Comment by mani200307** [comment]
![image](https://github.com/SurajPratap10/Imagine_AI/assets/89850065/c02f8a39-0e66-42f3-9b18-853721e36aa2)

@SurajPratap10, Does it look good?

**Comment by SurajPratap10** [comment]
Put it on the website and then share the pic @mani200307

**Comment by mani200307** [comment]
Yeah, I put it on the website and raised a PR
