### ISSUE TITLE
Feature: Login and Sign up ejs integration

### ISSUE THREAD

**Issue by PranavSikarwal** [SurajPratap10/Imagine_AI#107]
**Is your feature request related to a problem? Please describe.**

***Currently Login and Sign up pages are just landing html pages.***

![image](https://github.com/SurajPratap10/Imagine_AI/assets/85329574/d93cfe36-04d5-4c9c-b535-4e888c779305)

Integrate them with ejs to make project similar throughout, previously didn't integrate them to avoid multiple errors.

**Comment by SurajPratap10** [comment]
assigned @PranavSikarwal 📌
