### ISSUE TITLE
Nav Bar improvements [Hamburger]

### ISSUE THREAD

**Issue by PR1YAM9** [SurajPratap10/Imagine_AI#109]
Hi @SurajPratap10, As seen on the website the navbar is not responsive for phones and tablets as, Hamburger menu option for users is missing, adding a photo for reference 
<img width="147" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/92604300/40d3b449-d693-45f1-b3fc-dba38afa9160">
**Solution:**
I would like to add the hamburger menu option to make it better for user experience and make it responsive for all media widths.
### Reference video from past projects:
<img width="146" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/92604300/ea1ba71d-3385-44a3-8dc9-f18f5a89dc9e">

<img width="149" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/92604300/94c4a4d9-55bb-492b-9829-f8b195e66fc2">

Video reference(cant upload directly video>10mb)
https://www.kapwing.com/w/7wNlRBMUnj

Kindly assign me this issue under GGSOC.
Regards Priyam Maini

**Comment by PR1YAM9** [comment]
hi, Instead of home It should be Imagine-Ai or the brand logo for the universal back button.

**Comment by SurajPratap10** [comment]
Ok, go ahead @PR1YAM9 ✌
