### ISSUE TITLE
Addition of footer section

### ISSUE THREAD

**Issue by PR1YAM9** [SurajPratap10/Imagine_AI#110]
hey @SurajPratap10 , 
### Addition:
Footer: 1. A responsive footer with all your **contact links**, **services provided** by the website, and A **NewsLetter** to send emails to users about the new additions to the website. For example, in the future, a feature of Generative AI image Rendering has been added so for the user to know about it a small email would be the best.
**Reference image from previous projects:** 
<img width="960" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/92604300/f41342cf-ae80-4688-bb2b-cb4e6b77319b">

<img width="148" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/92604300/8d11a4fc-07bc-4024-ae44-7113254aa90d">

I think A footer would be a great addition as it increases the SEO score of the website and provides an easy navigation method to the users. I will make it by keeping proper SEO practices, the design of the website, and your suggestions in mind.

Kindly assign me this issue under GGSOC 23'
Regards Priyam Maini

**Comment by SurajPratap10** [comment]
Assigned @PR1YAM9
