### ISSUE TITLE
[style]: Improve Mobile Hamberger Menu Positioning and Fix Z-Index Overlap

### ISSUE THREAD

**Issue by rajveeerr** [SurajPratap10/Imagine_AI#1113]
### What's the style idea?

On mobile devices, certain elements like images overlap the hamberger menu, affecting its visibility and functionality. To resolve this issue, we need to improve the positioning of the hamberger menu and adjust the z-index to ensure it stays on top of other elements.

**Tasks:**
1. Adjust the positioning of the hamburger menu for better alignment on mobile devices.
2. Fix the z-index of the hamburger menu so it consistently appears above images and other content.
3. Test across different screen sizes and devices to ensure the fix works universally.

This improvement will enhance the overall user experience, especially on mobile platforms.

### Add screenshots

Screenshots

![Screenshot 2024-10-01 at 11 26 52 PM](https://github.com/user-attachments/assets/1fd48e9e-6239-4056-8e39-3dc8158f1f1f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
Go ahead ✌
