### ISSUE TITLE
[BUG] - Dark Mode not working at community page

### ISSUE THREAD

**Issue by dushyantkanav** [SurajPratap10/Imagine_AI#1139]
### Current behaviour

Dark Mode not working at community page

### Expected behaviour

Dark Mode have to working at community page

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

![DESCRIPTION](LINK.png)

### Are you contributing for a program ?

Other

### Checklist

- [X] I have checked the existing [issues](https://github.com/SurajPratap10/Imagine_AI/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/SurajPratap10/Imagine_AI/blob/main/CONTRIBUTING_GUIDELINES.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rajveeerr** [comment]
@dushyantkanav are you working on this
