### ISSUE TITLE
[style]: Inconsistent Font Styles Across Pages – Suggestion to Use Montserrat for Consistency on landing page

### ISSUE THREAD

**Issue by Dipu2552003** [SurajPratap10/Imagine_AI#1140]
### What's the style idea?

In the project, I noticed an inconsistency in the font styles used across various sections of the website. On the landing page, a cursive sans-serif font is being used, which is inconsistent with the Montserrat font applied on the "Contact Us" and "About Us" pages. Additionally, the input fields on the landing page use the same cursive font, while other pages lack uniformity.

To maintain visual consistency, I suggest updating the landing page font to Montserrat, ensuring uniformity across all sections of the website. This will create a more cohesive user experience and improve the overall design aesthetics.

![before](https://github.com/user-attachments/assets/a2805a4e-beb1-4a85-b2b8-22c7067fdb71)

### Add screenshots

Add screenshots
![mon](https://github.com/user-attachments/assets/d11b9442-fc81-4c6a-8750-ec41ae1d50ce)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajveeerr** [comment]
@shobhitexe what do you think about these changes??
