### ISSUE TITLE
[BUG] - Community Page is Not Responsive – Heading Font Size Issue

### ISSUE THREAD

**Issue by Dipu2552003** [SurajPratap10/Imagine_AI#1141]
### Current behaviour

Currently, the heading font on the Community Page does not scale properly when the page is resized or viewed on different devices. It remains small even on larger screens, making the page look unbalanced and not optimized for responsiveness. The font size should increase in proportion to the screen size, ensuring better visual hierarchy and readability across devices.
![community_page](https://github.com/user-attachments/assets/a9b0916d-7a09-4f7f-8621-31aeb5500417)

### Expected behaviour

The heading font on the Community Page should adapt responsively to different screen sizes. It should use a relative unit like rem so that on larger screens, the font size is appropriately bigger, and on smaller screens, it adjusts to a smaller, readable size. This ensures better readability and a user-friendly design across all devices.

### Reproduction steps

```bash
Go to the Community Page on the website through phone view.
Scroll down to view the entire page content 
See the error with the heading font size not adjusting based on screen size.
```

### Screenshots

![DESCRIPTION](LINK.png)
![community_page](https://github.com/user-attachments/assets/012c2f1a-cbe2-484b-8800-773f3ce4ddfb)

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

GSSoC23

### Checklist

- [X] I have checked the existing [issues](https://github.com/SurajPratap10/Imagine_AI/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/SurajPratap10/Imagine_AI/blob/main/CONTRIBUTING_GUIDELINES.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rajveeerr** [comment]
@Dipu2552003  you can start working on this
