### ISSUE TITLE
[BUG] - After Login, The login button on Navbar and Login Page also showing!

### ISSUE THREAD

**Issue by Vaibhav-Samdani** [SurajPratap10/Imagine_AI#1149]
### Current behaviour

After log in, Log in button on Navbar and Login Page also showing.

### Expected behaviour

After login, Login Button become Logout button and if anyone go to login page it automatically redirect to the Home page as he/she is already logged in.

### Reproduction steps

```bash
1. Login on Login page
2. Redirect to Generate Image page
3. There is a issue Login Button showing instead of log out button
4. and while going to Login page is also showing log in page instead of redirecting to the home or Generate Image page.


and also I am the contributor for gssoc-ext. please add the label of gssoc-ext and level2 as it is 2 problems.
```

### Screenshots

![image](https://github.com/user-attachments/assets/3653608d-77e9-4120-af5a-b23105f8d886)

![image](https://github.com/user-attachments/assets/e4b2c9e7-2d66-41eb-8599-7bc1d96cda8e)

### Browsers

All Browsers

### OS

Windows

### Are you contributing for a program ?

GSSoC23, Other

### Checklist

- [X] I have checked the existing [issues](https://github.com/SurajPratap10/Imagine_AI/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/SurajPratap10/Imagine_AI/blob/main/CONTRIBUTING_GUIDELINES.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by rajveeerr** [comment]
@Vaibhav-Samdani do you want to work on this?
