### ISSUE TITLE
[style]: Improve Breakpoints and Fix UI Overlap of Hamburger Menu and Dark Mode Toggle

### ISSUE THREAD

**Issue by rajveeerr** [SurajPratap10/Imagine_AI#1150]
### What's the style idea?

There are some responsiveness issues at certain screen sizes where the UI appears janky. Specifically, the **Hamburger Menu** and the **Dark Mode Toggle** are overlapping, which causes usability issues.

#### **Problem:**
- The UI doesn’t scale well on all screen sizes, leading to a janky appearance.
- The **Hamburger Menu** and the **Dark Mode Toggle** overlap at some breakpoints, making them hard to interact with.
  
#### **Expected Behavior:**
- Implement better breakpoints so that the UI looks consistent and smooth across all screen sizes.
- The **Hamburger Menu** and **Dark Mode Toggle** should have proper spacing and never overlap, regardless of screen size.

#### **Steps to Reproduce:**
```bash
1. Open the website on different screen sizes (between mobile and tablet sizes).
2. Notice that the UI becomes janky and the Hamburger Menu overlaps with the Dark Mode Toggle.
```

#### **Impact:**
- This affects the usability and visual appeal on some screen sizes, causing difficulty in accessing menu options and toggling dark mode.

#### **Checklist:**
- [x] I have checked the existing issues to avoid duplicates.
- [x] I have followed the contributing guidelines.

### Add screenshots

<img width="386" alt="Screenshot 2024-10-15 at 11 09 07 AM" src="https://github.com/user-attachments/assets/aed3ab99-262f-46f0-8525-8e76be65d563">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
@rajveeerr  don't assign labels to your own opened issues as eventually while merging I'll only assign the labels and those will only count. You can assign labels to issues of other folks just don't self assign rest Looks Good, Go Ahead with it✨

**Comment by rajveeerr** [comment]
Got it, sir! Just one thing—are we talking about the gssoc-extd and hactoberfest-accepted labels, or just the level ones?

**Comment by SurajPratap10** [comment]
@rajveeerr any label just don't self assign as it doesn't look professional to self assign ur own issue right.👍
