### ISSUE TITLE
[style]: The email in the footer is too conjusted

### ISSUE THREAD

**Issue by subin-shk** [SurajPratap10/Imagine_AI#1154]
### What's the style idea?

We need to improve on the email input in the footer. The space between icon and input field is conjusted making is visually unappealing.

### Add screenshots

Add screenshots
![image](https://github.com/user-attachments/assets/1b03ada6-6710-4cac-a76f-1a8201dcf69f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
go ahead @subin-shk
