### ISSUE TITLE
[BUG] - Lot fo UI fixes

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [SurajPratap10/Imagine_AI#1156]
### Current behaviour

https://github.com/user-attachments/assets/8504ae62-1191-42d2-861f-b300efc79789

### Expected behaviour

there are lot of Ui bugs like that in the page , @SurajPratap10 if u can assign me this ill fix them ASAP.

last issue i misclicked gssoc23, im in gssoc24-exntd

### Reproduction steps

```bash
-
```

### Screenshots

![DESCRIPTION](LINK.png)

### Browsers

Chrome

### OS

Mac

### Are you contributing for a program ?

Other

### Checklist

- [X] I have checked the existing [issues](https://github.com/SurajPratap10/Imagine_AI/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/SurajPratap10/Imagine_AI/blob/main/CONTRIBUTING_GUIDELINES.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by SurajPratap10** [comment]
already one guy is working on it, so I am closing this issue.You can find new issues
