### ISSUE TITLE
[UI Enhancement] : Adding GSAP animations to home page when loaded | gssoc-extd level 3

### ISSUE THREAD

**Issue by Hamza1821** [SurajPratap10/Imagine_AI#1173]
**Describe the solution you'd like**
Adding GSAP animations to home page when loaded

please assign this issue to me under gssoc-extd level 3

**Comment by rajveeerr** [comment]
@Hamza1821 level will be decided, by your pr

**Comment by SurajPratap10** [comment]
Go ahead @Hamza1821
