### ISSUE TITLE
[style]: [BUG] - Community Page Responsiveness and Display Grid Issues

### ISSUE THREAD

**Issue by rajveeerr** [SurajPratap10/Imagine_AI#1174]
### What's the style idea?

The community page has several responsiveness issues and needs to be fixed for a professional and polished appearance. The current problems include:

1. **Display Grid Responsiveness**: The display grid is not properly configured, causing elements to appear misaligned or overlapping when viewed on different screen sizes, especially mobile devices.
2. **Heading Size**: The heading uses viewport height (`vh`) units, leading to inappropriate sizing on smaller devices, making it look disproportionate and unprofessional.
3. **Mobile View**: The page completely breaks on mobile devices, with elements not adjusting properly to fit the screen.

**Tasks:**
- Adjust the grid settings to ensure proper responsiveness and alignment for all screen sizes (desktop, tablet, and mobile).
- Replace the heading units from `vh` to a more suitable approach (e.g., `rem` or a responsive font scaling solution) to maintain proper sizing across devices.
- Test the page on various devices and browsers to ensure it is fully responsive and professional-looking.

### Add screenshots

<img width="1280" alt="Screenshot 2024-10-08 at 7 16 45 PM" src="https://github.com/user-attachments/assets/cbbdbce4-cee0-4a05-9a39-6ed92ae444cf">
<img width="1280" alt="Screenshot 2024-10-08 at 7 53 26 PM" src="https://github.com/user-attachments/assets/27fff084-24af-4e94-af59-f50f25a1c00b">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
Go ahead @rajveeerr
