### ISSUE TITLE
[style]: improving UI for 2 forms.

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [SurajPratap10/Imagine_AI#1178]
### What's the style idea?

We need to improve  the forms of these 2 forms .
@SurajPratap10 if you can assign me this ill work on it asap.

### Add screenshots

Add screenshots
<img width="804" alt="Screenshot 2024-10-08 at 8 49 45 PM" src="https://github.com/user-attachments/assets/0fd79a41-9bca-4f34-8d45-0e2f69e1f732">
<img width="858" alt="Screenshot 2024-10-08 at 8 49 54 PM" src="https://github.com/user-attachments/assets/0aeee60e-78db-435f-8767-c0ffabddc906">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
Go ahead @T-Rahul-prabhu-38
