### ISSUE TITLE
Community Page - Overflow

### ISSUE THREAD

**Issue by SurajPratap10** [SurajPratap10/Imagine_AI#1180]
### Current behaviour

![image](https://github.com/user-attachments/assets/0f79d6c6-9787-4563-8eb1-45067848c4d3)

### Expected behaviour

- Fix the sizing of the community section in the navbar such that it doesn't overlaps with the text.

### Browsers

Chrome

### OS

Windows

**Comment by SurajPratap10** [comment]
It's a very beginner friendly issue so I will assign it to the person who comments first 👍

**Comment by rajveeerr** [comment]
please assign this to me, ill fix that
