### ISSUE TITLE
[BUG] - Missing 'Scroll to Top' Button on the Community Page

### ISSUE THREAD

**Issue by rajgharat07** [SurajPratap10/Imagine_AI#1185]
### Current behaviour

The Community Page does not have a "Scroll to Top" button. When users scroll down the page, they must manually scroll back up if they want to return to the top.

### Expected behaviour

A "Scroll to Top" button should be available on the Community Page. This button should appear once the user scrolls down a certain distance and, when clicked, should smoothly scroll the page back to the top for easier navigation.

### Reproduction steps

```bash
1. Go to 'https://imagine-ai-17zf.vercel.app/'
2. Click on 'COMMUNITY'
3. Scroll down to '....'
4. See error - Not showing Scroll to Top Btn
```

### Screenshots

![DESCRIPTION](LINK.png)
I am unable to add screenshot but you can verify.

### Browsers

Chrome

### OS

Windows

### Are you contributing for a program ?

Other

### Checklist

- [X] I have checked the existing [issues](https://github.com/SurajPratap10/Imagine_AI/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/SurajPratap10/Imagine_AI/blob/main/CONTRIBUTING_GUIDELINES.md)
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

**Comment by rajveeerr** [comment]
@rajgharat07 you can start working on this
