### ISSUE TITLE
[style]: Enhance Main Heading with Dynamic Hover Effect

### ISSUE THREAD

**Issue by sanchitc05** [SurajPratap10/Imagine_AI#1198]
### What's the style idea?

The main heading on the homepage currently appears static and could benefit from a more engaging design. The goal is to implement a hover effect that captures users' attention and encourages interaction.

**Proposed Changes:** 

_Background Transition:_

- Add a background color or gradient transition that changes on hover.
- Consider a shadow effect to create depth.

Kindly assign me this issue @SurajPratap10 

### Add screenshots

![Screenshot 2024-10-10 155525](https://github.com/user-attachments/assets/621a8549-52ee-4445-91a3-a3f9438917ab)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajveeerr** [comment]
@sanchitc05 GTG
