### ISSUE TITLE
Modifying signup page

### ISSUE THREAD

**Issue by avneet-singh843** [SurajPratap10/Imagine_AI#120]
**Describe the bug**
Few things that can be added to signup page:
1. add confirm password
2. There is no form validator(form can be submitted with empty fields)
3. Customised error message

Assign this issue to me under GSSOC'23

**Comment by SurajPratap10** [comment]
assigned @avneet-singh843

**Comment by avneet-singh843** [comment]
@SurajPratap10 thanks, is "GSSOC'23" label required?

**Comment by khushiminda** [comment]
so for a responsive UI UX-
i will-
Plan my layout
Use a responsive framework
Design for mobile-first
Use media queries
Test across devices
Provide touch-friendly interactions
I can make this more responsive.
assign this to me under gssoc'23.]

**Comment by avneet-singh843** [comment]
@SurajPratap10 created branch on my local desktop. But It is giving "permission denied". Can you help me out?
<img width="532" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/96073704/f2c3fe8d-45e9-4e9f-97b0-5b1929a97fbf">

**Comment by SurajPratap10** [comment]
Login and Signup page have been made functional recently , so just while updating please don't change anything. I suggest you to work with the recent repo.
