### ISSUE TITLE
[style]: Redesign and add more features to footer section

### ISSUE THREAD

**Issue by ShradhaSaxena23** [SurajPratap10/Imagine_AI#1208]
### What's the style idea?

**Objective:**

Redesign the footer layout with an updated color palette.
Add a "back to top" button for easy navigation.
Ensure the footer is fully responsive across all devices.
Incorporate social media icons and links.

I am eager to take on this issue, as I am a contributor in **GSSOCExt 2024 and hacktoberfest** . I kindly request that you assign this issue to me.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rajveeerr** [comment]
@ShradhaSaxena23 you can start working on this!!
