### ISSUE TITLE
[style]: Color Palette Update

### ISSUE THREAD

**Issue by snehas-05** [SurajPratap10/Imagine_AI#1224]
### What's the style idea?

**Here's what I propose-**
I think we should completely overhaul the website's color palette to introduce a sleek, dark theme that provides a contemporary, visually appealing experience for users. I've always found dark themes to be more modern and sophisticated, not to mention easier on the eyes, especially during long viewing sessions. For this redesign, the dark background should be complemented with vibrant accent colors, like electric blue or deep purple, which would make the generated images really stand out and catch users' attention. This change isn't just about aesthetics—it's about creating a more comfortable, enjoyable experience for our users. Implementing this upgrade would undoubtedly enhance the overall usability and attractiveness of the platform, making it not only more engaging but also more accessible and user-friendly. After all, a sleek and visually appealing interface can make a significant difference in how users perceive and interact with the platform. 

### Add screenshots

Add screenshots
![Screenshot 2024-10-13 164434](https://github.com/user-attachments/assets/8d5c11fb-1fc1-4941-9cc3-917c68a8f388)
I propose to change the color pallete

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
Go ahead @snehas-05 , I will directly assign the `level` in the PR as I can't see the developed site now
