### ISSUE TITLE
Feature: Modifying Tech Stacks in ReadMe

### ISSUE THREAD

**Issue by PranavSikarwal** [SurajPratap10/Imagine_AI#123]
**We can add a link to Documentation of Each Tech Stack in ReadMe.md**

**Basic Markdown design**
`[name](link)`

**Further we Can add `EJS` to the tech stack as it is the templating engine which is used.**

**Comment by PranavSikarwal** [comment]
@SurajPratap10 may you assign this issue to me under GSSOC'23

**Comment by SurajPratap10** [comment]
assigned @PranavSikarwal 📌
