### ISSUE TITLE
Improvement in mobile view of ContactUs Section

### ISSUE THREAD

**Issue by SasiVardhan247** [SurajPratap10/Imagine_AI#124]
**Is your feature request related to a problem? Please describe.**
When I'm viewing website in mobile the input text boxes are looking very small.
![Screenshot 2023-05-24 232740](https://github.com/SurajPratap10/Imagine_AI/assets/83742554/6649f128-206f-407b-a6ca-58369e59f7b6)

i want to improve it like this: @SurajPratap10 

![Screenshot 2023-05-24 233006](https://github.com/SurajPratap10/Imagine_AI/assets/83742554/236cc66f-c0d7-40ed-88a2-faceeaf87656)

Can you assign this issue to me. I'm in gssoc'23.

**Comment by SurajPratap10** [comment]
Assigned @SasiVardhan247 🔥
