### ISSUE TITLE
[NEW]: Improvement of navbar and home page design 

### ISSUE THREAD

**Issue by Ks103** [SurajPratap10/Imagine_AI#126]
**Is your feature request related to a problem? Please describe.**
yes, as website can be more better to this changes

**Describe the solution you'd like**
Improving design by adding some css can make the website more user friendly

**Describe alternatives you've considered**
Can also build designing and frontend part

**Additional context**
Request you to please assign me the task.

**Comment by 9520prashant** [comment]
Yep I am working on it .

**Comment by SurajPratap10** [comment]
Assigned @Ks103  go ahead ✨

**Comment by 9520prashant** [comment]
@Ks103 Let's discuss the thing (eg: what to improve in navbar).

**Comment by Ks103** [comment]
Sure

**Comment by Ks103** [comment]
Here are the designs and figma link

https://www.figma.com/file/a8pdJhaVBV13EQZtRTovod/Untitled?type=design&node-id=0%3A1&t=dmhho1bTa27pYKyF-1

![Desktop - 2](https://github.com/SurajPratap10/Imagine_AI/assets/86292101/c612f2d6-ae86-477c-ad02-bb8d701b57ed)
![Desktop - 1 (1)](https://github.com/SurajPratap10/Imagine_AI/assets/86292101/2a0d1327-c0a6-4664-9fa8-8e08c88d00da)

@9520prashant is working on the frontend part

**Comment by SurajPratap10** [comment]
Very Nice , just make the text more visible @Ks103 ⭐

**Comment by Ks103** [comment]
Sure it will be done
