### ISSUE TITLE
Footer alignment in Home Page 

### ISSUE THREAD

**Issue by 9520prashant** [SurajPratap10/Imagine_AI#13]
© Suraj Pratap 
Github is not align in Home Page.
You can see in Screen Shot
Please assign me this issue.
![Screenshot (223)](https://github.com/SurajPratap10/Imagine_AI/assets/99237795/a16efe04-d4d4-4ffd-a651-a0120c357c2e)

**Comment by SurajPratap10** [comment]
@9520prashant  assigned to you 🔥
