### ISSUE TITLE
Changes in Readme- How to Contribute?

### ISSUE THREAD

**Issue by SasiVardhan247** [SurajPratap10/Imagine_AI#130]
![image](https://github.com/SurajPratap10/Imagine_AI/assets/83742554/8f6f7fcd-509e-46dd-8f91-2f1bbf6b7eb1)

we should be cloning our forked project not the authors.(Clone your forked copy of the project.)

I think the cmd should be : git clone  https://github.com/<your_github_username>/Imagine_AI.

Can you assign this to me @SurajPratap10 .I'm in GSSOC'23

**Comment by SurajPratap10** [comment]
Assigned @SasiVardhan247
