### ISSUE TITLE
Adding a blogs section containg lastes ai news

### ISSUE THREAD

**Issue by AmanSingh6574** [SurajPratap10/Imagine_AI#138]
Similar to this it will help the user to get the updated and the latest news about ai

![image](https://github.com/SurajPratap10/Imagine_AI/assets/113782984/55751432-a4b9-4796-ac88-8e40f7f20754)

pls assign me this issue under GSSOC'23 label 
@SurajPratap10

**Comment by SurajPratap10** [comment]
Assigned @AmanSingh6574  ,  Go ahead 🔥
