### ISSUE TITLE
Adding an example of DALL-E 2.0 

### ISSUE THREAD

**Issue by AmanSingh6574** [SurajPratap10/Imagine_AI#139]
Adding pictures and information can help the user to know how to use this application correctly plus we can add the procedure or steps on how to get your own API key

![image](https://github.com/SurajPratap10/Imagine_AI/assets/113782984/bbeaed35-e380-4a77-ad77-b6e340526026)

pls assign me this issue under GSSOC'23 label 
@SurajPratap10

**Comment by SurajPratap10** [comment]
@AmanSingh6574  go ahead 📌

**Comment by AmanSingh6574** [comment]
@SurajPratap10  hello sir I was working on this issue but didn't know that u have also assigned the same task to someone else
 as this task is completed now I want to change the ui of the examples added as the image size is very huge leading to lagging of the site plus the prompt is also not visible clearly
I require your permission to start @SurajPratap10

**Comment by AmanSingh6574** [comment]
@SurajPratap10  sir you assigned me this task but this have been completed by someone else. I think you have assigned the same task

**Comment by SurajPratap10** [comment]
I don't remember this as there are so many PRs on a daily basis, plus you didn't respond for many days while other folks were raising PRs constantly so I might have forgotten about this. You may add some extra features and I will consider it @AmanSingh6574
