### ISSUE TITLE
Contact Page Submit Button

### ISSUE THREAD

**Issue by 9520prashant** [SurajPratap10/Imagine_AI#142]
positioning of submit button in contact page is not correct you can see in SS. kindly assign this issue to me @SurajPratap10 .

![Screenshot (249)](https://github.com/SurajPratap10/Imagine_AI/assets/99237795/b3176392-cfc4-458d-8396-50b53bda2ebe)

**Comment by 9520prashant** [comment]
This should be like that in center 

![Screenshot (250)](https://github.com/SurajPratap10/Imagine_AI/assets/99237795/fd0a4c00-74ab-499f-8128-fc0a6a51f8fb)

**Comment by SurajPratap10** [comment]
Assigned @9520prashant
