### ISSUE TITLE
Error on Signup Page

### ISSUE THREAD

**Issue by programerr01** [SurajPratap10/Imagine_AI#143]
Error on signup page for element not existing 

**To Reproduce**
1. Go to Signup Page
2. Click on Submit after filling in 

**Expected behavior**
It should submit the form 

![image](https://github.com/SurajPratap10/Imagine_AI/assets/61112300/96c603d0-e0fe-4544-a628-e3ed2304ee99)

**Comment by SurajPratap10** [comment]
Assigned @programerr01
