### ISSUE TITLE
Fix the Alignment of Images

### ISSUE THREAD

**Issue by SurajPratap10** [SurajPratap10/Imagine_AI#146]
**Describe the bug**
- The images should be aligned Horizontally
- Do take care about the responsiveness too

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/57bb1173-17df-4f89-842c-b9672104734f)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by laibaahsan27** [comment]
I can fix it for you. 
Please assign it to me @SurajPratap10

**Comment by SurajPratap10** [comment]
assigned @laibaahsan27 📌

**Comment by laibaahsan27** [comment]
hii @SurajPratap10 i can also improve the css of the text associated with the images 
![image](https://github.com/SurajPratap10/Imagine_AI/assets/123810454/18d18d31-4797-4a59-a546-fdca35c9b206)
currently it looks very basic. If i do this could you please increase the level of this issue.

**Comment by SurajPratap10** [comment]
> hii @SurajPratap10 i can also improve the css of the text associated with the images ![image](https://user-images.githubusercontent.com/123810454/241309838-18d18d31-4797-4a59-a546-fdca35c9b206.png) currently it looks very basic. If i do this could you please increase the level of this issue.

Ok , sure

**Comment by vk20july** [comment]
I want to work on this issue under gssoc'23
