### ISSUE TITLE
Revamp the contact us page

### ISSUE THREAD

**Issue by prernadabi23** [SurajPratap10/Imagine_AI#151]
The "Contact Us" page needs improvement in terms of its appearance. We can enhance it by applying attractive CSS styles and reorganizing its layout. A straightforward approach would be to create a clear header at the top, followed by the contact form, and finish with a visually appealing footer.

![Screenshot from 2023-05-26 15-47-26](https://github.com/SurajPratap10/Imagine_AI/assets/104578155/40d8aef2-13a6-4754-acd7-c5080f5bdfef)

**Comment by SurajPratap10** [comment]
assigned @prernadabi23
