### ISSUE TITLE
The backgrund color of the website

### ISSUE THREAD

**Issue by prernadabi23** [SurajPratap10/Imagine_AI#152]
The background color of the website detracts from its appeal and doesn't create the desired atmosphere or vibes.

**Comment by SurajPratap10** [comment]
assigned @prernadabi23

**Comment by prernadabi23** [comment]
How about this design? 

![Screenshot from 2023-05-28 14-34-13](https://github.com/SurajPratap10/Imagine_AI/assets/104578155/73d5bb57-61b2-481c-96c8-d5756975e1ab)

@SurajPratap10

**Comment by SurajPratap10** [comment]
Wouldn't pure white would look off?

**Comment by prernadabi23** [comment]
I have added the transparent texture before.
How about this one? I have added some animations too.
![Screenshot from 2023-05-29 15-23-01](https://github.com/SurajPratap10/Imagine_AI/assets/104578155/77ad4059-911d-4438-8055-63bc5d117873)

**Comment by SurajPratap10** [comment]
you can raise a PR , I will check and if needed then ask u to update by looking at the deployed site by vercel bot @prernadabi23

**Comment by prernadabi23** [comment]
Hello, @SurajPratap10 I have raised a PR.
Do you need any changes?
