### ISSUE TITLE
Implementing Login and Signup using JWT and Bcrypt [GSSOC'23]

### ISSUE THREAD

**Issue by kartikayasija** [SurajPratap10/Imagine_AI#154]
Login and Signup components are not functional. 
It can be implemented by bcrypt and jwt.

<img width="923" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/115306535/9a8fa553-2a5d-4a16-b6ce-66f64fa339ee">

**Comment by SurajPratap10** [comment]
@Shounmay is working on it
