### ISSUE TITLE
[Bug] : Home page front end Broke. 

### ISSUE THREAD

**Issue by PranavSikarwal** [SurajPratap10/Imagine_AI#157]
**Alignment of front page got affected after a PR was merged today though content of that PR is important**
![image](https://github.com/SurajPratap10/Imagine_AI/assets/85329574/2b15d51c-ebe1-430c-9e9f-3a2515d103d0)

And i Don't no why someone changed the footer include of EJS from home.ejs this is causing different lengths of navbar which is not good for user experience

You can easily see the visual difference in the lengths of nav bar this is due to removal of include of header.ejs in the home.ejs.

At home
![image](https://github.com/SurajPratap10/Imagine_AI/assets/85329574/8ad879aa-39d0-42d1-9ed7-1558004cf0b5)

At generate image
![image](https://github.com/SurajPratap10/Imagine_AI/assets/85329574/62f4b1f6-249f-4039-af1d-8914a19c3777)

**Will Fix the Styling of the page and find out the reason of alignment as soon as possible**

**They must be aligned in rows**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Comment by 9520prashant** [comment]
Yep Bro I am working on it you can also work on it with me if you have great idea for that

**Comment by PranavSikarwal** [comment]
@9520prashant now it got fixed somehow
![image](https://github.com/SurajPratap10/Imagine_AI/assets/85329574/9867bc57-b256-4be1-8536-f8680a0240c7)

**Comment by 9520prashant** [comment]
Hey @PranavSikarwal Issue has been fixed please close the issue
