### ISSUE TITLE
Adding scroll effects bar and back to top button.

### ISSUE THREAD

**Issue by somyakabra** [SurajPratap10/Imagine_AI#158]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The scroll effect bar and back-to-top button are presently not present. So I'll add.

**Describe alternatives you've considered**

**Additional context**
A beautifully functional and highly responsive behavior scroll bar and back-to-top button are to be added.
@SurajPratap10

**Comment by SurajPratap10** [comment]
@somyakabra  assigned

**Comment by vk20july** [comment]
I want to work on this issue under gssoc'23

**Comment by Prajwal0225** [comment]
If nobody currently working on this issue then 
@SurajPratap10 can you assign this issue to me I would like to do it.

**Comment by somyakabra** [comment]
I'll do this by the end of this weekend @SurajPratap10
