### ISSUE TITLE
Spacing between home section and footer

### ISSUE THREAD

**Issue by 9520prashant** [SurajPratap10/Imagine_AI#159]
Spacing between home section and footer is very few, kindly assign this small issue to me although i have fixed it @SurajPratap10 

![Screenshot (261)](https://github.com/SurajPratap10/Imagine_AI/assets/99237795/57857f42-d463-4316-b737-71e5a1270af7)

**Comment by PranavSikarwal** [comment]
@9520prashant your discord: prashant Varma #9241 is shown to be incorrect, please make sure you copy it correctly and provide it to me.

**Comment by SurajPratap10** [comment]
assigned @9520prashant
