### ISSUE TITLE
Bug: showLoading is not defined

### ISSUE THREAD

**Issue by SurajPratap10** [SurajPratap10/Imagine_AI#16]
**Describe the bug**
- Image is not loading while generating it from the `OpenAI` api key.

**To Reproduce**
1. Go to the 'Imagine_AI website'
2. Give proper 'Image Description
3. Click on 'Generate'
4. Scroll down 
5. See an error

**Expected behavior**
https://www.youtube.com/watch?v=FR3i1GmtiEA

**Screenshots**
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/5dafefd8-c509-46b3-a314-858a9cd21a07)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aditya9277** [comment]
I want to work on this issue. I am GSSoC 23 contributor and want to contribute by fixing this issue.

**Comment by parthpathakpp1** [comment]
I want to work on this issue . I can fix this issue very fast . You can assign this issue to me

**Comment by SurajPratap10** [comment]
Assigning it to you @parthpathakpp1 🔥

**Comment by parthpathakpp1** [comment]
> Assigning it to you @parthpathakpp1 🔥

Sorry @SurajPratap10 I tried lot of things but could not fix the issue and do not want to waste your time . You can assign the issue to someone else.

**Comment by SurajPratap10** [comment]
No problem, the person who want to work may ask here for the `assign`

**Comment by harmeetsingh11** [comment]
I'm in GSSOC'23. Can I try to resolve this issue?

**Comment by harmeetsingh11** [comment]
I am not getting this error @SurajPratap10. It works as expected.

**Comment by vk20july** [comment]
can i work on this issue?
