### ISSUE TITLE
[Bug] Different Nav bars for different pages

### ISSUE THREAD

**Issue by PranavSikarwal** [SurajPratap10/Imagine_AI#162]
**Describe the bug**
1- We use ejs to include the nav bar so that nav bar remains same throught the project but through a PR header includes were removed and a new nav bar was added.

2- Previously a highlight nav bar item feature was present which made particular page visited to be highlighted when visited.
![image](https://github.com/SurajPratap10/Imagine_AI/assets/85329574/e98cd75e-6ef9-4b53-8e51-a78d3cd5b975)

**To Reproduce**
1. Again inject the include of header in home.ejs

**Expected behavior**
Same lengths of nav in all the pages.

WE can notice the different lengths of nav bars

home nav bar
![image](https://github.com/SurajPratap10/Imagine_AI/assets/85329574/860524e7-ac3e-4459-baf9-1119f5cbae7d)

other nav bar
![image](https://github.com/SurajPratap10/Imagine_AI/assets/85329574/713e6fba-4b95-4c68-9cd8-c67f3ec52d21)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome]

Additionally you can see this, there should else be a include of header.ejs include.
![image](https://github.com/SurajPratap10/Imagine_AI/assets/85329574/b2266c15-6ec1-47cc-a3d1-9b8f0ee69e7a)

**Comment by PranavSikarwal** [comment]
@SurajPratap10 if pr 166 i.e. Navfix works and fixes everything without an error than maybe this issue is not relevant, 
else if not than i will fix the includes portion so that no more conflicts are faced when developing nav bar.
Due to different nav bars on different pages, there might be issues in later developments which can cause major conflicts, hence there is a urgent need to fix such an issue. 
Please close this issue only after merging pr 166 and after it works fine.

**Comment by SurajPratap10** [comment]
Fix it @PranavSikarwal 👍
