### ISSUE TITLE
PRELOADER!!!!

### ISSUE THREAD

**Issue by laibaahsan27** [SurajPratap10/Imagine_AI#163]
**Is your feature request related to a problem? Please describe.**
Your website does not have a preloader and I would like to make it.

I think this preloader will be suitable for your website, it is animated which makes it very appealing. I will customize the colours according to your website.
![image](https://github.com/SurajPratap10/Imagine_AI/assets/123810454/297e411f-4ba6-482d-ae15-854614bf169f)

@SurajPratap10  If you like my idea then assign it to me under the label GSSOC 2023.

**Comment by 9520prashant** [comment]
@laibaahsan27 Awesome

**Comment by SurajPratap10** [comment]
assigned 

> @laibaahsan27 Awesome

@9520prashant  Please don't comment on others issue until needed as it creates confusion on who is actually working on it 👍

**Comment by SurajPratap10** [comment]
Assigned @laibaahsan27 📌
