### ISSUE TITLE
Error on Submit in Login Page

### ISSUE THREAD

**Issue by programerr01** [SurajPratap10/Imagine_AI#164]
Error on login page for element not existing
it's similar to #143 

To Reproduce

Go to Login Page
Click on Submit after filling in
Expected behavior
It should submit the form
![image](https://github.com/SurajPratap10/Imagine_AI/assets/61112300/66ec09ea-9b81-4e82-9c9b-668c77ef93af)

**Comment by SurajPratap10** [comment]
@programerr01  assigned 📌
