### ISSUE TITLE
Fix : Additions in the Issue template

### ISSUE THREAD

**Issue by Anshika-Jain02** [SurajPratap10/Imagine_AI#167]
## Description:

*I noticed that the repository does not have an appropriate issue template*

*Issue Template: I want to add some more template options in your issue template like Style changes, documentation, etc. It will provide more convenience to the users*

**Please assign this issue to me under Gssoc'23 @SurajPratap10**

**Comment by SurajPratap10** [comment]
assigned @Anshika-Jain02 📌
