### ISSUE TITLE
Protecting routes

### ISSUE THREAD

**Issue by Shounmay** [SurajPratap10/Imagine_AI#171]
**Is your feature request related to a problem? Please describe.**
As of Now any user can signup and login. But that's of no use until we protect the route that only logged in user can generate images.

**Describe the solution you'd like**
We can generate access tokens for logged in users and store it in localstorage. As the user will open the generate image page, we can check with the access token for checking that the user is authenticated or not.

**Describe alternatives you've considered**
If the above conventional method fails, we can use third party API services to achieve it. Moreover if there is certain security concern over getting access token from localstorage, we can store it in MongoDb and after each request from user to open generate image url, we can make a backend APi call to fetch and validate access token session.

**Additional context**
I am GSSOC'23 contributor. Could you assign this issue to me and add labels to it. @SurajPratap10

**Comment by SurajPratap10** [comment]
Assigned @Shounmay 📌

**Comment by Deepanshu0703** [comment]
is this issue is still available as i wanna work on it

**Comment by AlfiyaSiddique** [comment]
Waiting in the queue to work on this issue
