### ISSUE TITLE
Fixing the navbar and the footer

### ISSUE THREAD

**Issue by PoulavBhowmick03** [SurajPratap10/Imagine_AI#172]
**Is your feature request related to a problem? Please describe.**
The navbar doesn't look pleasing as compared to the rest of the webpage and the color change is too fast
Also, the icons at the bottom are quite large for their size
**Describe the solution you'd like**
Fix the font size and their styling in the navbar, make the navbar sticky, and reduce the icon sizes

**Describe alternatives you've considered**
We can also add a little box shadow to the navbar to like have a cooler look

**Comment by SurajPratap10** [comment]
Already assigned to someone, you can look for new problems/features and raise issue.
