### ISSUE TITLE
[FEATURE] Adding Scrolling Transition effect in Home Page

### ISSUE THREAD

**Issue by Mahitej28** [SurajPratap10/Imagine_AI#173]
Hello, I am Mahima Churi, a proud contributor of GSSoc ' 23.

📌 I would like to work on this project by adding a transition effect while scrolling on Home Page, to give a dynamic look to that section.

📌 Also I would like to enhance the UI of the navbar by adding some icons and logo of the website and improving the font family.

If you think it is legit then do assign me the issue under GSSoC '23 with the level of the PR as well

**Comment by SurajPratap10** [comment]
Assigned to you @Mahitej28 📌

**Comment by Mahitej28** [comment]
Thank you I would move ahead with it, also as currently my exams are going on is it ok if I complete it by the first week of June

**Comment by harshit-tiwaari** [comment]
Assign this work to me SIr.I have already done that as i build a ecommerce website were i used it and i am free now .Hope i get a positive response

**Comment by Mahitej28** [comment]
@harshit-tiwaari kindly look into assigned people before raising an issue

**Comment by SurajPratap10** [comment]
> 

I have already assigned it to @Mahitej28 , you can look for new features/bugs and raise a new issue @harshit-tiwaari  if you want to contribute.
