### ISSUE TITLE
Want to improve the style of font 

### ISSUE THREAD

**Issue by HimanshuNarware** [SurajPratap10/Imagine_AI#174]
**Is your feature request related to a problem? Please describe.**
I want to improve the font of the website, It will improve the UI of the website and also improves the readability of the website

**Describe the solution you'd like**
The current Font of the website is not looking very attractive and user-friendly i want to solve this problem in the website 

**Additional context**
##Screenshot

![41](https://github.com/SurajPratap10/Imagine_AI/assets/83147410/bd275bab-292a-4f77-ab37-3c6c5a1b89d1)

**Comment by SurajPratap10** [comment]
Assigned @HimanshuNarware

**Comment by bilalshaikh292** [comment]
Heyy is the issue still open ? I would Like to Contribute.
