### ISSUE TITLE
Issue in Examples Section

### ISSUE THREAD

**Issue by SasiVardhan247** [SurajPratap10/Imagine_AI#175]
![image](https://github.com/SurajPratap10/Imagine_AI/assets/83742554/d6eabddc-ee1d-4b8b-8641-f21a540523f8)

I want to fix it @SurajPratap10 . There's an bug in that section ,can you assign this issue to me. I'm in GSSOC'23

**Comment by SurajPratap10** [comment]
Assigned @SasiVardhan247
