### ISSUE TITLE
Navbar Responsiveness 

### ISSUE THREAD

**Issue by 9520prashant** [SurajPratap10/Imagine_AI#185]
Navbar need responsiveness in styling kindly this issue to me @SurajPratap10 

![Screenshot (269)](https://github.com/SurajPratap10/Imagine_AI/assets/99237795/2b23f13d-69df-4720-8c47-f2a445056b8c)

**Comment by SurajPratap10** [comment]
Assigned @9520prashant

**Comment by PranavSikarwal** [comment]
Hi @9520prashant, someone has imported bootstrap that is why home nav bar is somehow differently behaving than other nav bars, if you can fix that bootstrap issue than it would be awesome.

**Comment by 9520prashant** [comment]
Hey @PranavSikarwal I tried but the navbar still not responsive and I can't find css code for very small screen

**Comment by PranavSikarwal** [comment]
@9520prashant yes, that is what i also felt was hard to correct someone either has to make navbar bootstrapped or just make cards for which bootstrap was to be plain css, maybe next time you can fix it.
