### ISSUE TITLE
Contributor Page

### ISSUE THREAD

**Issue by 9520prashant** [SurajPratap10/Imagine_AI#186]
Hey @SurajPratap10 I want to design contributor page for IMAGINE-AI  can you please assign me this feature

**Comment by SurajPratap10** [comment]
Assigned @9520prashant

**Comment by 1Shubham7** [comment]
@SurajPratap10 Its been a week. Can you please assign it to me now? I will get the work done in  a day or else unassign me.

**Comment by 9520prashant** [comment]
@1Shubham7 I have done but in backend i am facing some problem and i talked to @SurajPratap10 for this issue if you know backend then kindly help me

**Comment by 1Shubham7** [comment]
I would love to, I mostly use Django for backend but  I can try helping you. But how do you want me to help you.

**Comment by 9520prashant** [comment]
> 

ping me at discord, my Id: prashant Varma#9241

**Comment by 1Shubham7** [comment]
ok

**Comment by 1Shubham7** [comment]
but I don't know how to use discord butI will try
