### ISSUE TITLE
Addition of carousel in "SOME EXAMPLES OF IMAGES GENERATED THROUGH DALL-E2" 

### ISSUE THREAD

**Issue by medhacodes** [SurajPratap10/Imagine_AI#189]
**Is your feature request related to a problem? Please describe.**
The present website does not have this feature of a carousel.

**Describe the solution you'd like**
I will add a carousel to this section to make it more beautiful and unclustered.

**Describe alternatives you've considered**

**Additional context**

@rishuraj1 please assign this issue to me.

**Comment by SurajPratap10** [comment]
Assigned @medhacodes
