### ISSUE TITLE
Backend connection ERROR

### ISSUE THREAD

**Issue by 9520prashant** [SurajPratap10/Imagine_AI#190]
You can see the error in Screen Shot Below:

![Screenshot (270)](https://github.com/SurajPratap10/Imagine_AI/assets/99237795/043566b6-8f7e-4486-a90d-258ea1309a07)

Hey @SurajPratap10 If you know who developed backend then please resolve this issue as much as possible

**Comment by abhijeetnishal** [comment]
Hey @9520prashant this issue is due to importing mongoDB URI from .env file which is missing.
You can create in .env file and then it works fine.

**Comment by PranavSikarwal** [comment]
@9520prashant if you have worked on the issue, please close this issue, if your PR got merged.
