### ISSUE TITLE
Missing Contributing.md

### ISSUE THREAD

**Issue by Anshika-Jain02** [SurajPratap10/Imagine_AI#192]
*Missing Contributing guidelines file in the repo to provide clear guidelines to the contributors. I can add it*

**Please assign me this issue under Gssoc'23 @SurajPratap10**

**Comment by SurajPratap10** [comment]
Assigned @Anshika-Jain02

**Comment by Vishalk91-4** [comment]
@Anshika-Jain02 are you working on this issue, if not please let me solve this it's just a file with guidelines

**Comment by Anshika-Jain02** [comment]
@Vishalk91-4 yes, i am working on it and recently my exams are going on due to which there is a delay from my side in solving this issue.

**Comment by Vishalk91-4** [comment]
@SurajPratap10 can I work on this issue, if @Anshika-Jain02 agrees, both can fix this issue faster

**Comment by SurajPratap10** [comment]
> @SurajPratap10 can I work on this issue, if @Anshika-Jain02 agrees, both can fix this issue faster

Ya, ask her
