### ISSUE TITLE
Navigation bar styling issue due to bootstrap clashes

### ISSUE THREAD

**Issue by PranavSikarwal** [SurajPratap10/Imagine_AI#194]
**Describe the bug**
Home Navigation bar styling was disturbed due to addition of cards through bootstrap, now bootstrap classes of navbar do not allow navbar to inherit main styling as it is on other pages.

**To Reproduce**
I will change the class of nav bar in html and css to a unique class so that it do not clash with bootstrap

**Expected behavior**
Navbar will then be similar on all the pages and behave similarly

**Screenshots**
Compare home navbar with other navbar in screenshots below
![image](https://github.com/SurajPratap10/Imagine_AI/assets/85329574/87153c66-185c-4723-86fd-e205fed76dc2)
![image](https://github.com/SurajPratap10/Imagine_AI/assets/85329574/8b1607ea-4576-4b38-a07b-c970801fe408)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
The `login` , `OpenAI API` is not centered wrt to navigation bar.
![image](https://github.com/SurajPratap10/Imagine_AI/assets/85329574/b6e2bf60-51dd-4a21-805d-59b9951fba52)

**Comment by SurajPratap10** [comment]
Assigned @PranavSikarwal
