### ISSUE TITLE
Footer should contain the link that directs to privacy policy page and year of copyright

### ISSUE THREAD

**Issue by Suhaani07** [SurajPratap10/Imagine_AI#199]
A link should be added to connect with privacy policy page. It should also contain the copyright year.
<img width="232" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/98284331/3c286d3e-7738-467a-bb0a-2952f5e69bd8">

Please assign me this under gssoc 2023.

**Comment by SurajPratap10** [comment]
Assigned @Suhaani07
