### ISSUE TITLE
GSSoC'23 - Improved UI

### ISSUE THREAD

**Issue by abrehan2** [SurajPratap10/Imagine_AI#2]
I have visualized your web app and it needs to have an improved UI and better responsiveness. Please assign this task to me, I will improve the responsiveness and make some necessary changes to the UI if needed <br>
![Screenshot (82)](https://github.com/SurajPratap10/Imagine_AI/assets/100872683/9136898e-e299-4174-90c0-2d1caa2e986f) <br>
![Screenshot (83)](https://github.com/SurajPratap10/Imagine_AI/assets/100872683/0cc580a3-e9c1-41a3-9962-f418856c925b)

**Comment by sumitkr2000** [comment]
Hey @SurajPratap10 Can I work on this issue?

**Comment by abrehan2** [comment]
> Hey @SurajPratap10 Can I work on this issue?

I'm already working on it!

**Comment by abrehan2** [comment]
> Hey @SurajPratap10 Can I work on this issue?

I'm already working on this issue.

**Comment by SurajPratap10** [comment]
> Hey @SurajPratap10 Can I work on this issue?

@abrehan2  has already been assigned on this, so if u wish you can work on other issues.

**Comment by sumitkr2000** [comment]
@SurajPratap10  There is bug in loading images but i don't know tthe tecnology used. How can i fix it? If you can help it would be great.

**Comment by SurajPratap10** [comment]
> @SurajPratap10 There is bug in loading images but i don't know tthe tecnology used. How can i fix it? If you can help it would be great.

There isn't a bug as such if you will run the whole project on your local device providing the `OpenAI API key`  in your `env` file then it will run just while deploying the whole site the backend is giving some issues which are open for folks to solve rest the project will run fine in your local device.  

- And if you have any doubts about Tech Stacks and stuff do read the Readme file, there I have mentioned every info and also provided a `WORKING VIDEO` (YouTube) of the site.

**Comment by sumitkr2000** [comment]
ok thank you @SurajPratap10

**Comment by sumitkr2000** [comment]
Is there any other thing on which I can work ?

**Comment by SurajPratap10** [comment]
> Is there any other thing on which I can work ?

Just check the `issues` section regularly and be the first to get the beginner-level issues assigned by me.

**Comment by sumitkr2000** [comment]
@SurajPratap10 ok bro thanks I'll let you know

**Comment by abrehan2** [comment]
Hi Suraj,
I hope this finds you well. I have pushed all the changes in a
separate branch but can't find a way to make a PR.

Link: https://github.com/abrehan2/Imagine_AI/tree/GSSoC-23

Best regards,
Rehan

[image: image.png]

**Comment by abrehan2** [comment]
Suraj, I was working on the issue that was assigned to me. Why can't I find
it? Why is this closed? It was working on it. I couldn't do it earlier
because of exams but now when I did I can't find my own issue that I
created earlier. Did you close it?

**Comment by abrehan2** [comment]
Hi @SurajPratap10,

I trust this message reaches you in good health. I have successfully committed all the modifications to a separate branch. However, I'm currently facing an issue when attempting to create a pull request. When I click on "compare and PR," the interface does not display a field to enter any text.
