### ISSUE TITLE
Add logout in routes and controller

### ISSUE THREAD

**Issue by abhijeetnishal** [SurajPratap10/Imagine_AI#200]
**Describe the bug**
Logout route is missing in auth routes at backend

**Expected behavior**
Logout route with functionality is implemented in backend.
This enhancement will enable users to securely log out from their accounts, ensuring privacy and data protection.

**Comment by abhijeetnishal** [comment]
Please assign me this task under GSSOC 2023.

**Comment by SurajPratap10** [comment]
Assigned 📌  @abhijeetnishal
