### ISSUE TITLE
[style]: Adding image beside home page text

### ISSUE THREAD

**Issue by Shr-reny** [SurajPratap10/Imagine_AI#209]
### What's the style idea?

We need to improve  the main home page which is a plain text.  We can add an image to improve the look.

### Add screenshots

Add screenshots 
![Artificial-Intelligence-removebg-preview](https://github.com/SurajPratap10/Imagine_AI/assets/125943681/fcda5cfd-6971-48f7-a635-9eb17cc38345)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
assigned @Shr-reny
