### ISSUE TITLE
[style]: 

### ISSUE THREAD

**Issue by DhyanShah22** [SurajPratap10/Imagine_AI#212]
### What's the style idea?

We need to improve  the home page looks off we can add the shadow effect and the blur effect instead of the color theme and a better background color as well as the filter

### Add screenshots

Add screenshots
![Screenshot from 2023-05-31 14-05-48](https://github.com/SurajPratap10/Imagine_AI/assets/115366189/e7aea773-0982-443d-a2fd-db0b49c71dc3)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DhyanShah22** [comment]
Please assign this to me under GSSOC'23

**Comment by SurajPratap10** [comment]
assigned @DhyanShah22
