### ISSUE TITLE
Add Pull Request Template 

### ISSUE THREAD

**Issue by andoriyaprashant** [SurajPratap10/Imagine_AI#214]
**Describe the bug**
- Adding a PR template
- Template path .github\pull_request_template.md

**Screenshots**
![Screenshot 2023-05-29 233408](https://github.com/SurajPratap10/Imagine_AI/assets/121665385/71990055-7e97-4103-b9f6-63e4ccf146c7)
![Screenshot 2023-05-29 233534](https://github.com/SurajPratap10/Imagine_AI/assets/121665385/3638e937-721a-4bdf-b083-0c63cdb05584)

**Additional context**
GSSOC 2023

**Comment by andoriyaprashant** [comment]
Hello @SurajPratap10 
Please assign me this issue 
Thank you

**Comment by andoriyaprashant** [comment]
Hey @SurajPratap10 
Please review my Pull request #215 
Thank you

**Comment by SurajPratap10** [comment]
assigned @andoriyaprashant

**Comment by andoriyaprashant** [comment]
@SurajPratap10 Thank you for merging my pull request with the GSSOC title. But can you please add the GSSOC level to this issue's pull request(#215) as well? Otherwise, my pull request won't count. 
Thank you for your support
