### ISSUE TITLE
Adding OAuth authentication for signing in with google

### ISSUE THREAD

**Issue by AKsHaT123456A** [SurajPratap10/Imagine_AI#217]
**Is your feature request related to a problem? Please describe.**
Signing in with google will increase the ease to log in for the user.

**Describe the solution you'd like**
i could like to implement it with OAuth.

**Comment by Visbhavesh** [comment]
I'm a contributor for GSSoC '23, I want to contribute to this issue. Please assign me.

**Comment by SurajPratap10** [comment]
assigned @AKsHaT123456A

**Comment by AKsHaT123456A** [comment]
Hi @SurajPratap10 do you want it for both sign in and sign up?

**Comment by SurajPratap10** [comment]
> Hi @SurajPratap10 will you share env?

like share to ?

**Comment by SurajPratap10** [comment]
> Hi @SurajPratap10 do you want it for both sign in and sign up?

Ya, it would be nice

**Comment by AKsHaT123456A** [comment]
Okay the work is completed will send some screenshots then will raise a PR.

**Comment by AKsHaT123456A** [comment]
![image](https://github.com/SurajPratap10/Imagine_AI/assets/104546329/a37c3d8a-60d5-4c60-8591-1c0006604efb)
Hi @SurajPratap10 have completed my work should i raise a PR?

**Comment by AKsHaT123456A** [comment]
Hi @SurajPratap10 kindly review my PR

**Comment by AKsHaT123456A** [comment]
@SurajPratap10 it won't work unless you have given your client and server key in envs...kindly see into that....while testing i myself generated these keys
