### ISSUE TITLE
[style]: Adding Mockup design to Login button

### ISSUE THREAD

**Issue by shubham-shinde-442** [SurajPratap10/Imagine_AI#218]
### What's the style idea?

We need to improve  login button by adding mockup and attractive hover over this.

As a Contributor in GSSOC"23 , I Would like to Work on this issue.

### Add screenshots

Add screenshots

![Screenshot (872)](https://github.com/SurajPratap10/Imagine_AI/assets/123376721/81f3200a-4595-4edf-a621-de43ad549afa)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
assigned @shubham-shinde-442
