### ISSUE TITLE
[Fix]: Card image behavior on Chrome- Fix

### ISSUE THREAD

**Issue by PranavSikarwal** [SurajPratap10/Imagine_AI#222]
**Is your feature request related to a problem? Please describe.**
Images behave inappropriately on chrome vs other browser
![image](https://github.com/SurajPratap10/Imagine_AI/assets/85329574/7311e36f-681b-4b3f-aa79-84c15cf0d0c9)

**Describe the solution you'd like**
I am not sure but according to this solution on stack-overflow, adding max-width of container to 200% might work.
reference: https://stackoverflow.com/questions/40237393/responsive-image-behaves-differently-in-chrome-and-safari

**Describe alternatives you've considered**
Would work on assigning particular values of width or ask community members to engage, and work on this issue if they have a better approach.

**Additional context**
https://stackoverflow.com/questions/40237393/responsive-image-behaves-differently-in-chrome-and-safari

**Comment by SurajPratap10** [comment]
assigned @PranavSikarwal
