### ISSUE TITLE
Footer style change

### ISSUE THREAD

**Issue by Suhaani07** [SurajPratap10/Imagine_AI#225]
### What's the style idea?

Should we try a simple dark themed footer instead of the current one which as the same background effect as that of the body. Something like in this given picture.

### Add screenshots

<img width="413" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/98284331/4204cec6-4024-486d-9eaa-408c2ea4b198">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
assigned @Suhaani07
