### ISSUE TITLE
A modal warning for wrong API key 

### ISSUE THREAD

**Issue by shobhitexe** [SurajPratap10/Imagine_AI#226]
**Is your feature request related to a problem? Please describe.**
Like if i put wrong API key i should get some warning like "Api key is not valid" instead of "Error: The image was not generated" as seen in attached SS coz users should be aware of what exactly causing error 

**Describe the solution you'd like**
We can apply Regex to validate API key or some sort of error handling while submitting POST request to backend

**Additional context**
![image](https://github.com/SurajPratap10/Imagine_AI/assets/29349136/26b9abd4-9483-4da6-8327-4ad8996aec4a)

**Comment by SurajPratap10** [comment]
ASSIGNED @shobhitexe
