### ISSUE TITLE
[GSSOC'23][style]:  Textarea tag does not use the same font as input tags in contact form.

### ISSUE THREAD

**Issue by ayushkumarbhadani** [SurajPratap10/Imagine_AI#228]
### What's the style idea?

It looks like the textarea tag under the "Give your Valuable Feedback" Label does not use the same font as input tags.

I want to work on this, please assign this issue to me under GSSOC'23.

### Add screenshots

# Screenshots

<img width="722" alt="Screenshot 2023-06-02 at 4 35 58 PM" src="https://github.com/SurajPratap10/Imagine_AI/assets/73775939/a4d028bf-78ed-44e8-bc74-3121f253ae6e">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
assigned @ayushkumarbhadani

**Comment by ayushkumarbhadani** [comment]
Fixed by @Shtolle, I'm closing this issue.
