### ISSUE TITLE
The Password in log-in page is not hidden. [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [SurajPratap10/Imagine_AI#233]
**Describe the bug**
When we go to the log in page the password is not hidden therefore anyone can see you type your password.

**To Reproduce**
1. Go to Login Page
2. Click on Password

**Expected behavior**
Password must be hidden like *********

**Screenshots**
![password seen](https://github.com/SurajPratap10/Imagine_AI/assets/116020663/44b5a885-783f-41f1-a5fa-b0ead1a7ea1d)

**Additional context**
Please assign me this issue under GSSoC'23.

**Comment by 1Shubham7** [comment]
Please assign me this issue under GSSoC'23

**Comment by SurajPratap10** [comment]
Assigned @1Shubham7

**Comment by 1Shubham7** [comment]
@SurajPratap10 Thank you soo much for assigning.

**Comment by 1Shubham7** [comment]
Thank you @SurajPratap10
