### ISSUE TITLE
Movie Recommendation system 

### ISSUE THREAD

**Issue by 15IITian** [SurajPratap10/Imagine_AI#234]
Hi, I am  15IITian , as a ML enthusiast , want to create a ml model which will recommend movies based on user interest which is a crucial feature of many famous brands like Netflix.
Dataset link-https://www.kaggle.com/datasets/grouplens/movielens-20m-dataset
Please assign this interesting project to me:)

**Comment by amankumar100** [comment]
Please approve my contribution. It works perfectly.
