### ISSUE TITLE
[style]: Redesign contact us page

### ISSUE THREAD

**Issue by Pragati-3003** [SurajPratap10/Imagine_AI#237]
### What's the style idea?

I would like to change the ui  of the contact us page by changing its design and adding some cool effects .

### Add screenshots

![iai](https://github.com/SurajPratap10/Imagine_AI/assets/132778037/b6b6e920-7581-4a45-b00d-69192fafa0b0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
Assigned @Pragati-3003
