### ISSUE TITLE
[style]: Change ui of cards in home page

### ISSUE THREAD

**Issue by Pragati-3003** [SurajPratap10/Imagine_AI#238]
### What's the style idea?

I would like to change the ui of the cards in home page.
![Screenshot 2023-06-04 124650](https://github.com/SurajPratap10/Imagine_AI/assets/132778037/efe8dd6f-f17b-4644-aad1-b0e9f2a1d491)
I Would like to add some cool effects and box shadow also ,i would like to add flipper ,So ,please assign this to me under gssoc'23.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
I think the current effect is cool enough , still you can show a demo video of your enhancement.

**Comment by Pragati-3003** [comment]
> I think the current effect is cool enough , still you can show a demo video of your enhancement.

okie ,I'll share you a vedio once the design will ready.
