### ISSUE TITLE
[style]: Issue with contact us Page

### ISSUE THREAD

**Issue by ATOMworkplace** [SurajPratap10/Imagine_AI#239]
### What's the style idea?

![imagine-ai-3](https://github.com/SurajPratap10/Imagine_AI/assets/114564628/312afe64-e923-421a-959a-9778393e146d)
We need to improve  
Submit button is not aligned properly, it is overlapping with other content on the page.
**This is what it looks like currently***
![before-imagine-ai](https://github.com/SurajPratap10/Imagine_AI/assets/114564628/ce104216-5f45-4c05-af40-56c9acda0099)
![before-imagine-ai-1](https://github.com/SurajPratap10/Imagine_AI/assets/114564628/ca8c732b-7334-49a0-bd5c-78a0d3bde9e7)

I can make the required changes and align it properly.

![imagine-ai](https://github.com/SurajPratap10/Imagine_AI/assets/114564628/d31d8bd9-b6c4-44c1-9518-55656f7c6419)

![imagine-ai-2](https://github.com/SurajPratap10/Imagine_AI/assets/114564628/9ca0aa32-fb8f-4752-9c0f-fcf6243c1e1a)

### Add screenshots

**Currently**
![before-imagine-ai](https://github.com/SurajPratap10/Imagine_AI/assets/114564628/ce69d7f2-5dea-405c-938d-941f473574a9)
![before-imagine-ai-1](https://github.com/SurajPratap10/Imagine_AI/assets/114564628/0d329fcc-6cc8-4f7a-9d14-50765ffd937e)

**After changes**

![imagine-ai](https://github.com/SurajPratap10/Imagine_AI/assets/114564628/e32a23f1-bf37-4b61-9f68-d84a3d25c651)
![imagine-ai-2](https://github.com/SurajPratap10/Imagine_AI/assets/114564628/f3190478-7b06-4c9e-8f69-fc21ab17438f)
![imagine-ai-3](https://github.com/SurajPratap10/Imagine_AI/assets/114564628/fe86a0f5-7847-49d8-b57b-9a6ad7a3cb17)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ATOMworkplace** [comment]
I would like to work on this issue. I have already made changes, Please assign me this issue so that I can submit PR, under GSSOC'23

**Comment by SurajPratap10** [comment]
I have assigned this issue to someone, wait until that is being done then I will reply you regarding this issue

**Comment by SurajPratap10** [comment]
Assigned @ATOMworkplace
