### ISSUE TITLE
Bug: wrong cursor on text and api field

### ISSUE THREAD

**Issue by stuti-09** [SurajPratap10/Imagine_AI#24]
On hovering over text and api field pointer cursor is showing but it should be text cursor.
I want to work on this issue. Please assign me this issue under gssoc'23.

**Comment by SurajPratap10** [comment]
> On hovering over text and api field pointer cursor is showing but it should be text cursor. I want to work on this issue. Please assign me this issue under gssoc'23.

assigned @stuti-09

**Comment by stuti-09** [comment]
I have resolved the issue and made the pull request. Please review it.
