### ISSUE TITLE
[style]: Enhancing the Design of Contact Us page in Mobile View

### ISSUE THREAD

**Issue by Vishalk91-4** [SurajPratap10/Imagine_AI#244]
### What's the style idea?

We need to improve  
I want to sort the code for Mobile version in the order, so that it doesn't break and then I'll make the necessary styles changes as needed

@SurajPratap10 could you please assign this issue to me

### Add screenshots

Add screenshots
![Screenshot_20230604-221904](https://github.com/SurajPratap10/Imagine_AI/assets/116670999/28f261a7-d604-4a8e-9604-374f425408b6)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
I have already assigned this issue to someone as per now, so I am closing this issue
