### ISSUE TITLE
Subscribe to Us need Improvement

### ISSUE THREAD

**Issue by 9520prashant** [SurajPratap10/Imagine_AI#258]
The Subscribe to Us Section looks very different to the theme of the Website so I tried to Improve that according theme 

**Before**

https://github.com/SurajPratap10/Imagine_AI/assets/99237795/a9817951-eabd-424d-8039-2de4bc138d69

**After**

https://github.com/SurajPratap10/Imagine_AI/assets/99237795/d17ffd05-8c44-4d13-a156-0eb4791b4a90

**Additional context**
Hey @SurajPratap10 Kindly assign this issue to me under GSSOC.

**Comment by SurajPratap10** [comment]
For now it looks nice, In future updates you can change it

**Comment by 9520prashant** [comment]
but I red color looks Wired

**Comment by SurajPratap10** [comment]
> but I red color looks Wired

I assigned you the `Home` section work so enhance it under that only @9520prashant . No need for creating seperate issues for this 👍

**Comment by 9520prashant** [comment]
Sure
