### ISSUE TITLE
Paragraph Tag Size in Small Screen 

### ISSUE THREAD

**Issue by 9520prashant** [SurajPratap10/Imagine_AI#26]
You can see the issue in P Tag in small screen 
Hey @SurajPratap10 I have fixed it please assign this issue to me.

![Screenshot (229)](https://github.com/SurajPratap10/Imagine_AI/assets/99237795/1f3c15fa-3199-4e98-8b4c-52df0e0c2013)

**Comment by SurajPratap10** [comment]
Go ahead @9520prashant 🔥
