### ISSUE TITLE
Home Section Improvement 

### ISSUE THREAD

**Issue by 9520prashant** [SurajPratap10/Imagine_AI#260]
Hey @SurajPratap10 I tried to Improve home section with logo of IMAGINE-AI and some animation, please assign me this issue under GSSOC.

**Result**

https://github.com/SurajPratap10/Imagine_AI/assets/99237795/69d248c2-10d3-4010-8369-62ef7144b725

**Comment by SurajPratap10** [comment]
assigned @9520prashant , You raise a PR and I will address the changes
