### ISSUE TITLE
make Contact us section Functional: Interactive Phone Number and Email Integration

### ISSUE THREAD

**Issue by Mrprayag077** [SurajPratap10/Imagine_AI#271]
**Describe the bug**

**To Reproduce**
1. Go to 'footer'
2. Scroll down to '....'
3. Click on 'phone number or email'
4. something should occur like open dial pad or for email the Gmail window should open

**Expected behavior**

In the footer section of the website, the contact information is currently static and non-functional. To improve user experience and interaction, I propose the implementation of interactive functionality for the phone number and email. This feature will enhance usability by enabling users to easily interact with the contact details based on their device.

    **Phone Number Functionality:**

On mobile devices, clicking the phone number will automatically open the dial pad with the number pre-populated for effortless calling.

On desktop devices, clicking the phone number will copy the number along with the contact name to the clipboard, facilitating easy access for users.

    **Email Integration:**

Clicking the email address will automatically open a new email window in the default email client, with the sender's email address pre-filled for seamless communication.

**AND a few additions** like  **The footer logo-text [Imagine-AI]** should be made clickable, redirecting users to the home page. This will provide a seamless and intuitive navigation experience, allowing users to easily return to the main page.

 when users **submit their information in the "Subscribe to us"** section, only a text button is displayed. This can sometimes leave users unsure if their submission was successful or not. To address this, it is recommended to display a proper modal container upon form submission. This container will provide clear and visible feedback, confirming the successful submission and ensuring users are aware that their information has been received.
 
 **plz assign this task under the GSSOC-23 program** 

**Screenshots**

![Screenshot (1201)](https://github.com/SurajPratap10/Imagine_AI/assets/99162236/007741e1-d8b4-4bed-8f48-674ec7a06eb6)

**Additional context**
By implementing these interactive features, users will have a more streamlined and convenient way to engage with the contact information, resulting in an improved overall user experience.

**Comment by SurajPratap10** [comment]
Assign @Mrprayag077

**Comment by Mrprayag077** [comment]
I hope this message finds you well. I wanted to inform you that I have made some significant changes to the project as per the task assigned under the GSSOC-23 program. I have implemented the following improvements: (also improved mobile compatibility)



**Subscription Form Feedback:**

- Upon form submission in the "Subscribe to us" section, a proper modal container is now displayed, providing clear and visible feedback to users. This confirms the successful submission and ensures users are aware that their information has been received.
- email id validation added 
- alert send if email id format wrong

**Phone Number Functionality:**

- Popup displayed  [Mobile Number copied]
- On desktop devices, clicking the phone number will copy the number along with the contact name to the clipboard, facilitating easy access for users.
- On mobile devices, clicking the phone number will automatically open the dial pad with the number pre-populated for effortless calling.


**Email Integration:**

- Popup displayed [Email id copied]
- Clicking the email address now automatically opens a new email window in the default email client, with the sender's email address pre-filled for seamless communication.

**Footer Logo-Text:**

- The footer logo text, "Imagine-AI," has been made clickable, redirecting users to the home page. This provides a seamless and intuitive navigation experience, allowing users to easily return to the main page.



https://github.com/SurajPratap10/Imagine_AI/assets/99162236/857a5480-1682-44db-be45-d012ff385e17



I have recorded a video showcasing these changes for your review. You can access the video. I would like to request permission to submit a pull request to incorporate these changes into the project.

**Comment by Mrprayag077** [comment]
@SurajPratap10 

> I hope this message finds you well. I wanted to inform you that I have made some significant changes to the project as per the task assigned under the GSSOC-23 program. I have implemented the following improvements: (also improved mobile compatibility)
> 
> **Subscription Form Feedback:**
> 
> * Upon form submission in the "Subscribe to us" section, a proper modal container is now displayed, providing clear and visible feedback to users. This confirms the successful submission and ensures users are aware that their information has been received.
> * email id validation added
> * alert send if email id format wrong
> 
> **Phone Number Functionality:**
> 
> * Popup displayed  [Mobile Number copied]
> * On desktop devices, clicking the phone number will copy the number along with the contact name to the clipboard, facilitating easy access for users.
> * On mobile devices, clicking the phone number will automatically open the dial pad with the number pre-populated for effortless calling.
> 
> **Email Integration:**
> 
> * Popup displayed [Email id copied]
> * Clicking the email address now automatically opens a new email window in the default email client, with the sender's email address pre-filled for seamless communication.
> 
> **Footer Logo-Text:**
> 
> * The footer logo text, "Imagine-AI," has been made clickable, redirecting users to the home page. This provides a seamless and intuitive navigation experience, allowing users to easily return to the main page.
> 
>  imagine-ai.mp4 
> I have recorded a video showcasing these changes for your review. You can access the video. I would like to request permission to submit a pull request to incorporate these changes into the project.

@SurajPratap10  plz review the changes for PR

**Comment by Mrprayag077** [comment]
@SurajPratap10, could you please review: I have completed the goal **Contact us section Functional**  I would like to create a pull request to merge these updates. Thank you!

**Comment by Mrprayag077** [comment]
@SurajPratap10 plz check my changes so i can create a pull request

**Comment by Mrprayag077** [comment]
@SurajPratap10, **it has been quite a while since I made the changes. I kindly request you to create a pull request.

**Comment by Mrprayag077** [comment]
@SurajPratap10, **it has been quite a while since I made the changes. I kindly request you to create a pull request.**
