### ISSUE TITLE
feat: Sticky navbar

### ISSUE THREAD

**Issue by SINJINI-G** [SurajPratap10/Imagine_AI#276]
Hi @SurajPratap10 !! I will make the navbar sticky. Can you please assign this issue to me for gssoc?

**Comment by SurajPratap10** [comment]
Assigning it to you @SINJINI-G . And I am closing rest of your issues for now as according to gssoc rules we can't assign 4-5 issues to the same person at the same time. Do raise a new issue after you complete the previous one.
