### ISSUE TITLE
Popup Text is overflowing and not visible

### ISSUE THREAD

**Issue by crocmons** [SurajPratap10/Imagine_AI#281]
Popup Text is overflow and not visible ..I want to make it visible & improve the UI ... Could you please assign this issue to me as a GSoc23 contributor?
![Screenshot (420)](https://github.com/SurajPratap10/Imagine_AI/assets/106610322/8aa122f5-ab34-4dd6-909a-8cb9c07237f5)

**Comment by SurajPratap10** [comment]
Assigned @crocmons
