### ISSUE TITLE
[style]: Enhance Footer UI

### ISSUE THREAD

**Issue by crocmons** [SurajPratap10/Imagine_AI#282]
I want to work on this ...Could you please assign this issue to me as a GSSoc23 contributor?

Add screenshots

Before:
![Screenshot (421)](https://github.com/SurajPratap10/Imagine_AI/assets/106610322/19d0f7ae-ba75-479a-a373-120eccdda0dd)

After Demo:
![screenshot-dribbble com-2023 06 09-14_15_46](https://github.com/SurajPratap10/Imagine_AI/assets/106610322/13f55637-42e4-4057-a709-10d046228ad9)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krspriya** [comment]
i am ready to help

**Comment by SurajPratap10** [comment]
Assigned @crocmons

**Comment by SurajPratap10** [comment]
> i am ready to help

Good to know @krspriya, if you both wanna collaborate then do tell me then I will assign this to both of you. 
Just ask @crocmons  first 👌

**Comment by crocmons** [comment]
yeah, sure @krspriya can work on this..

**Comment by Vishalk91-4** [comment]
@crocmons , @SurajPratap10 actually I've already been assigned this and I'm working on it

**Comment by SurajPratap10** [comment]
> @crocmons , @SurajPratap10 actually I've already been assigned this and I'm working on it under issue #265

You work on it, whose footer will be better that I will merge? As there are so many folks that want to work on same issues and I can't deny to everyone

**Comment by Vishalk91-4** [comment]
@SurajPratap10 Sure, Thanks 
Could you send the link of Imagine-AI personal discord, so that I could join it
