### ISSUE TITLE
Remove console messages

### ISSUE THREAD

**Issue by Avinash905** [SurajPratap10/Imagine_AI#285]
**Describe the bug**
There are console.log messages getting displayed on the browser console tab which are not required and also not a good practice.

**To Reproduce**
1. Go to 'Sign up page' or 'Home page' 
2. We can see them on the console tab

**Expected behavior**
Remove all the unnecessary console.log messages from the code

**Screenshots**
![Screenshot (465)](https://github.com/SurajPratap10/Imagine_AI/assets/56786344/e57d7bbd-1164-4796-9f25-a0a8c424d48e)

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by SurajPratap10** [comment]
Tell me after doing the assigned issues then I will reopen this issue for you

**Comment by Avinash905** [comment]
> Tell me after doing the assigned issues then I will reopen this issue for you

Ok

**Comment by Avinash905** [comment]
@SurajPratap10, I have completed all the other issues assigned to me so could you reopen this issue.
