### ISSUE TITLE
Email validation to Subscribe to us section

### ISSUE THREAD

**Issue by Avinash905** [SurajPratap10/Imagine_AI#286]
**Describe the bug**
There is no email validation to the **Subscribe to us** section due to which we can enter any random string in the input and send.

**To Reproduce**
1. Go to 'Subscribe to use'
2. Type any text in the 'email input'
3. Click on 'Send button'
5. It will be sent even if it is not a valid email

**Expected behavior**
Add validation to email input of the Subscribe to us section.

**Screenshots**
![Screenshot (467)](https://github.com/SurajPratap10/Imagine_AI/assets/56786344/ed2510d3-486c-4c3d-96bf-fa7ff9056bda)

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by SurajPratap10** [comment]
@Avinash905  assigned to you
