### ISSUE TITLE
Validation to all inputs in Contact US form

### ISSUE THREAD

**Issue by Avinash905** [SurajPratap10/Imagine_AI#287]
**Describe the bug**
The contact us form does not have any input validations for first name, last name, email or phone number.

**To Reproduce**
1. Go to 'Contact Us' page
2. Fill the form with any random details
3. Click on 'Submit'
5. It does not give any error even if the inputs are invalid

**Expected behavior**
Validation to all inputs of form should be added.

**Screenshots**
![Screenshot (466)](https://github.com/SurajPratap10/Imagine_AI/assets/56786344/b8f8dbe8-dda7-49d3-90f9-302bdb868fd7)

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by SurajPratap10** [comment]
Assigned @Avinash905
