### ISSUE TITLE
add a New FAQ Page for Enhanced User Experience

### ISSUE THREAD

**Issue by Mrprayag077** [SurajPratap10/Imagine_AI#289]
**Describe the bug**
Adding a FAQ (Frequently Asked Questions) section to the website can significantly improve user experience. The FAQ section serves as a valuable resource for users, providing them with answers to commonly asked questions and addressing their concerns or queries. By including this dedicated section, users can easily find the information they need without having to search through multiple pages or contact customer support. The FAQ section will contribute to a more efficient and satisfying user experience, increasing user engagement and reducing potential friction points.

**Expected behavior**
The expected behavior is to add a FAQ (Frequently Asked Questions) section to the website. This section will provide users with answers to commonly asked questions and address their concerns or queries. Users should be able to access the FAQ section easily from the website's navigation menu or a designated FAQ page. The FAQ section should be well-organized, with questions and corresponding answers presented in a clear and concise manner.

**Additional context**
The addition of a FAQ section will enhance the user experience on the website. It will provide users with a centralized resource to find answers to their questions, reducing the need for them to search through multiple pages or contact customer support. The FAQ section should cover a wide range of topics relevant to the website's content or services, ensuring that users can easily find the information they need. The questions and answers should be regularly updated to reflect any changes or updates to the website or its offerings.

**plz assign this task under the GSSOC-23 program**

**Comment by SurajPratap10** [comment]
Already assigned this to a person before and he is working on it. You can raise new issues☑️
