### ISSUE TITLE
"Confirm password" field in Sign-Up form

### ISSUE THREAD

**Issue by vaibhav5140** [SurajPratap10/Imagine_AI#290]
**Is your feature request related to a problem? Please describe.**
I have noticed that our current sign-up form lacks a confirm password field. This omission poses a potential problem as users may mistype their passwords during registration, leading to account access issues and user frustration. So it will enhance the user experience and improve security,.

**Describe the solution you'd like**
The solution I propose is to include a confirm password field in the sign-up form. This additional field would require users to re-enter their chosen password, ensuring that they have typed it correctly. By comparing the password entered in the original password field with the one entered in the confirm password field, we can validate and confirm their password selection.

**Describe alternatives you've considered**
While there are alternatives to implementing a confirm password field, they may not provide an optimal user experience or ensure the same level of security, we can add a toggle(eye) button so that user can see the password.

**Additional context**
It helps prevent potential login issues caused by password typos and gives users confidence that they have successfully chosen their desired password. By implementing this feature, we can enhance the overall user experience and promote a more secure registration process for our platform.

**Comment by vaibhav5140** [comment]
Please assign me this issue so that I can work on this issue under GSSOC'23.

**Comment by SurajPratap10** [comment]
Assigned @vaibhav5140

**Comment by Bhuvanchand26** [comment]
Hey @SurajPratap10 , I've had experience in this validation. Please assign me this issues under GSSoC'23.
THANK YOU
