### ISSUE TITLE
Redesigning the 404 Page for Improved User Experience, current page UI lags 

### ISSUE THREAD

**Issue by Mrprayag077** [SurajPratap10/Imagine_AI#291]
**Describe the bug:**
The current 404 page on the website does not match the overall theme and design of other pages, resulting in a poor user experience. When users encounter a 404 error, they are presented with a visually inconsistent and potentially confusing page that does not align with the website's branding. This inconsistency can lead to frustration and a negative perception of the website.

**Expected behavior:**
The expected behavior is to upgrade the 404 page to align with the overall theme and design of other pages on the website. The upgraded 404 page should reflect the branding and visual style of the website, providing a consistent user experience. It should display a clear and informative message indicating that the requested page could not be found, along with relevant suggestions or links to help users navigate to other parts of the website.

**Screenshots**

![Screenshot (1240)](https://github.com/SurajPratap10/Imagine_AI/assets/99162236/7f719bf9-fc57-43b3-86a0-7780d1a31e86)

**Benefits:**

Enhanced user experience: A well-designed and visually consistent 404 page improves user experience by maintaining the overall look and feel of the website. Users will feel more confident and reassured, even when encountering errors or broken links.

- Brand consistency: The upgraded 404 page ensures brand consistency throughout the website, reinforcing the website's identity and creating a cohesive experience for users.
 
- Increased user engagement: By providing helpful suggestions or links on the 404 page, users are encouraged to explore other parts of the website, reducing bounce rates and increasing overall user engagement.
 
- Positive perception: A visually appealing and user-friendly 404 page leaves a positive impression on users, showcasing the website's attention to detail and commitment to providing a seamless browsing experience.
 
- Error recovery: The upgraded 404 page can help users recover from the error more easily by providing alternative options or guiding them to relevant content. This reduces frustration and improves the chances of users staying on the website.
 
- Professionalism: A well-designed 404 page demonstrates professionalism and attention to user needs, instilling trust and credibility in the website and its content.

plz assign this task under the GSSOC-23 program

**Comment by SurajPratap10** [comment]
Assigned @Mrprayag077

**Comment by Mrprayag077** [comment]
thank you for assigning me the task

**Comment by Mrprayag077** [comment]
Hello, @SurajPratap10! I have created a new theme for the 404 page. Please review it and note that it is now more mobile-friendly than the previous theme.

 Additionally, **I have added two more themes for the 404 page**. Please review them and let me know which theme you think looks best. Personally, I suggest that the **_first theme is good and looks professional_.**

I have shared a video to demonstrate the themes.

https://github.com/SurajPratap10/Imagine_AI/assets/99162236/0100e7f3-1485-4a25-adac-206605ad87c2

**Comment by Mrprayag077** [comment]
@SurajPratap10, could you please review the recent changes I made to a new theme for **404 PAGE**  I would like to create a pull request to merge these updates. Thank you!

**Comment by SurajPratap10** [comment]
> @SurajPratap10, could you please review the recent changes I made to a new theme for **404 PAGE** I would like to create a pull request to merge these updates. Thank you!

Just make a PR, don't wait for my reply as there are so many issues coming so I might only look the recent ones 

If u complete the issue then raise a PR instantly
