### ISSUE TITLE
Missing alt attribute in img tags

### ISSUE THREAD

**Issue by Avinash905** [SurajPratap10/Imagine_AI#296]
**Describe the bug**
The alt attribute is missing from many img tags. The alt attribute provides alternative information for an image if a user for some reason cannot view it (because of a slow connection, an error in the src attribute, or if the user uses a screen reader).

**Expected behavior**
Add proper alt attribute to all img tags present in this project for user experience

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by SurajPratap10** [comment]
Assigned @Avinash905
