### ISSUE TITLE
Give Border Radius to generate button [GSSOC'23]

### ISSUE THREAD

**Issue by kartikayasija** [SurajPratap10/Imagine_AI#3]
**Describe the bug**
The Generate button UI should match with input fields.

**To Reproduce**

**Expected behavior**
It should have same border radius and other UI enhancements.

**Screenshots**
<img width="949" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/115306535/5999cfac-1a5a-42c2-aa5d-50d1675e78f6">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Please assign this issue to me.

**Comment by SurajPratap10** [comment]
Great!! go ahead🔥
