### ISSUE TITLE
Navbar hiding details in contact us section

### ISSUE THREAD

**Issue by kumar11jr** [SurajPratap10/Imagine_AI#307]
**Describe the bug**
The navbar in the contact section is hiding some part of the form .

**To Reproduce**
1. Go to  contactus page
2. Scroll down and scroll up.
3. See error

**Expected behavior**
it is hiding the first name and last name label of the form.

**Screenshots**

https://github.com/SurajPratap10/Imagine_AI/assets/104729493/559cf03d-6439-40ad-9a02-9383f6bd0eec

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kumar11jr** [comment]
@SurajPratap10  kindly assign me this.....

**Comment by SurajPratap10** [comment]
Assigned @kumar11jr
