### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by stuti-09** [SurajPratap10/Imagine_AI#31]
There is no section which tell us about the website. I want to add this so that user can understand what website is about.
Please assign me this under gssoc'23.

**Comment by SurajPratap10** [comment]
Assigning it to you @stuti-09

**Comment by stuti-09** [comment]
I have made the pull request. Please review it and merge it.

**Comment by stuti-09** [comment]
I have also  fixed the issue#34 in this pull request.
