### ISSUE TITLE
Update contributors to the README.md

### ISSUE THREAD

**Issue by kunalnandre** [SurajPratap10/Imagine_AI#316]
I would like to update the profile images of the contributors in the README.md file because I think they appear too small in comparison to the rest of the page and other sections of the README.md.

Preview:-

![smallcontributors](https://github.com/SurajPratap10/Imagine_AI/assets/111383966/347d79fe-72a5-48bb-a10f-43ccbdc6ec38)

After solving this issue it will also keep updating itself as new contributors are added to project!

## Please have a look and assign this issue to me under GsSOC'23.

**Comment by SurajPratap10** [comment]
Assigned @kunalnandre

**Comment by kunalnandre** [comment]
I have added this issue can you please review it and close this issue by accepeting and merging the pull request under GSSoC'23
