### ISSUE TITLE
More Login Options and improved Signin and Signup UI

### ISSUE THREAD

**Issue by rishuraj1** [SurajPratap10/Imagine_AI#319]
Currently there is only one other option to login and sign up that is via Google. It is a classic button which does not look appealing

Proposed changes:

 - I believe, to make the login ui more appealing and user friendly, we should add more options like facebook and github.
 - Also, We might want to improve the ui of login and sign up page.

current: 

<img width="960" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/47839626/0058fb6a-b5d4-4571-83e6-cff4774e0f76">

I really want to contribute to this wonderful project. Please assign me to this under GSSoC '23. Thank You!

**Comment by SurajPratap10** [comment]
assigned @rishuraj1
