### ISSUE TITLE
Adding Image link in About Us

### ISSUE THREAD

**Issue by Vishalk91-4** [SurajPratap10/Imagine_AI#326]
The link to Image file is wrongly attached in About Us Page
![Screenshot_20230615-135846](https://github.com/SurajPratap10/Imagine_AI/assets/116670999/83cdf26d-18d4-4427-8db2-1785f310e9f6)
I will change that to the one where it shows imagine written in phone and laptop

@SurajPratap10 could you please assign this issue to me

**Comment by SurajPratap10** [comment]
assigned @Vishalk91-4
