### ISSUE TITLE
Decrease the MARGIN 

### ISSUE THREAD

**Issue by SurajPratap10** [SurajPratap10/Imagine_AI#34]
**Is your feature request related to a problem? Please describe.**
- Provide some gap as shown in the pics below

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

- There should be some gap between the `IMAGE DESCRIPTION` and the div end.
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/c77ffe82-5f37-4bb5-9448-eb99990db3e0)

- Make it like this
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/de089d1f-f0c1-4b1b-8bff-465ffd9cef19)

**Comment by Mansi1236** [comment]
I would like to work on this issue under GSSoC'23, kindly assign it to me.

**Comment by SurajPratap10** [comment]
I am closing this issue as this has already been solved in the previous PR , you can check for another issues and work on them @Mansi1236
