### ISSUE TITLE
Create a contributors page

### ISSUE THREAD

**Issue by karthiknadar1204** [SurajPratap10/Imagine_AI#340]
Proposed solution:
Implement a contributors page which will be routed on the navbar, this page shall have the avatar of all the contributors in the form of cards along with links which shall redirect the user to their github accounts.

The avatar and the link will be beautifully aligned in different cards.The contributors will be placed in descending order of the pr's made to the project.

**Comment by karthiknadar1204** [comment]
I would like to work on this issue inder gssoc'23

**Comment by SurajPratap10** [comment]
Assigned to you @karthiknadar1204

**Comment by karthiknadar1204** [comment]
Thank you

**Comment by karthiknadar1204** [comment]
@SurajPratap10 Heads up, will be pushing the changes by tomorrow, thank you for your patience

**Comment by karthiknadar1204** [comment]
@SurajPratap10 I have the api ready to make the fetch request, there are issues with setting up the project, after npm start, I am constantly getting this error
<img width="1395" alt="Screenshot 2023-06-22 at 2 20 19 PM" src="https://github.com/SurajPratap10/Imagine_AI/assets/95973644/d60b7b91-1a04-414a-9f0a-934167b6e317">

**Comment by karthiknadar1204** [comment]
How to proceed

**Comment by AlfiyaSiddique** [comment]
Hello @SurajPratap10 

Waiting in the queue to work on this issue.

**Comment by karthiknadar1204** [comment]
Issues setting up the project,almost done
