### ISSUE TITLE
[style]: Enhancing the Design of Contact Us Page

### ISSUE THREAD

**Issue by Vishalk91-4** [SurajPratap10/Imagine_AI#344]
### What's the style idea?

We need to improve the design of Contact Us Page

Adding some visuals/animations to it, not just changing the margin
Making a complete Page

### Add screenshots

Add screenshots![Screenshot 2023-06-16 211355](https://github.com/SurajPratap10/Imagine_AI/assets/116670999/b62cb4d2-b7ac-4b7c-aa85-59375ce9d4fe)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

@SurajPratap10 could you please assign this issue to me

**Comment by SurajPratap10** [comment]
Assigned to you @SurajPratap10
