### ISSUE TITLE
[style]: Making the Navbar Responsive

### ISSUE THREAD

**Issue by Vishalk91-4** [SurajPratap10/Imagine_AI#345]
### What's the style idea?

We need to improve  the responsiveness of Navbar and add a clickable to it, which would list out the headings for devices with smaller width

@SurajPratap10 could you please assign it to me

### Add screenshots

Add screenshots
Current
![Screenshot 2023-06-16 211416](https://github.com/SurajPratap10/Imagine_AI/assets/116670999/0255643a-2b88-44fe-935f-b16c7f15e14f)
![Screenshot 2023-06-16 211429](https://github.com/SurajPratap10/Imagine_AI/assets/116670999/74dc972f-22e3-43f7-91f4-38c852e9e3e0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
Assigned @Vishalk91-4
