### ISSUE TITLE
[style]: Aligning data in the About Us Page more

### ISSUE THREAD

**Issue by Vishalk91-4** [SurajPratap10/Imagine_AI#346]
### What's the style idea?

We need to improve  the alignment of data in about us page
I found that the sizes of texts were not compatible in the smaller devices,they look very good till 800-900 px , but breaks for less than that and the socials in testimonials were not properly aligned

@SurajPratap10 could you please assign this issue to me

### Add screenshots

Add screenshots
Current
![Screenshot 2023-06-16 223258](https://github.com/SurajPratap10/Imagine_AI/assets/116670999/8014e8fc-48d1-488f-8a33-f682151a4a94)
![Screenshot 2023-06-16 222952](https://github.com/SurajPratap10/Imagine_AI/assets/116670999/626a567a-d830-4ba1-9b2d-f2151eedb20c)
![Screenshot 2023-06-16 223312](https://github.com/SurajPratap10/Imagine_AI/assets/116670999/02583e6b-ce34-4dfc-87a3-00cc76bf2a2b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
I can't assign so many issues to a single person so do the previous ones then open this

**Comment by Vishalk91-4** [comment]
@SurajPratap10 , Sure, sorry if any conflict got created
