### ISSUE TITLE
Centre the text of the GENERATE Button

### ISSUE THREAD

**Issue by SurajPratap10** [SurajPratap10/Imagine_AI#35]
**Is your feature request related to a problem? Please describe.**
- Just add some more `right` value in the `GENERATE` button's CSS to center it.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Before
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/1329730f-eee7-4e43-aed3-819c17cd34d3)

After
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/09ed168e-7909-45c8-bb6f-a37ec9c25e47)

**Comment by Mansi1236** [comment]
I would like to work on this issue under GSSoC'23, please assign it to me

**Comment by SurajPratap10** [comment]
Assigning it to you @Mansi1236 

Just center the text (pic from current site)
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/e5bc5337-3ff2-490c-93a3-e1db47ba349f)
