### ISSUE TITLE
[style]: Adding carousel to Testimonial Section [Why People Choose Imagine-AI] section

### ISSUE THREAD

**Issue by abhi03ruchi** [SurajPratap10/Imagine_AI#350]
### What's the style idea?

We need to improve the testimonial section. 
I would like to add an automatic carousel instead of the cards for this section.
This would improve the user experience and engagement by making the site more cool and attractive.

Plz assign this issue to me under gssoc'23.

### Add screenshots

https://github.com/SurajPratap10/Imagine_AI/assets/105661636/19bbb234-c529-457d-ba91-b31154e8237b

Plz assign me this issue under gssoc'23/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abhinav-m22** [comment]
@SurajPratap10 Can I work on this issue if it is inactive?
Please assign me!
