### ISSUE TITLE
Improve lighthouse report score

### ISSUE THREAD

**Issue by Avinash905** [SurajPratap10/Imagine_AI#356]
**Is your feature request related to a problem? Please describe.**
The Performance, SEO, and Best practices score is low which might affect the overall experience of the user.

**Describe the solution you'd like**
I would like to fix these metrics of the website.

The current lighthouse score is:
![Screenshot (504)](https://github.com/SurajPratap10/Imagine_AI/assets/56786344/b13f9556-aebd-45d1-9459-a72b53526c26)

**Comment by Avinash905** [comment]
Please assign me this issue so that I can work on this issue under **GSSOC'23**.

**Comment by SurajPratap10** [comment]
Assigned @Avinash905
