### ISSUE TITLE
[style]: Updating readme.md file

### ISSUE THREAD

**Issue by AmanSingh6574** [SurajPratap10/Imagine_AI#359]
### What's the style idea?

the image is not loaded properly 
adding a proper image of the website

### Add screenshots

![image](https://github.com/SurajPratap10/Imagine_AI/assets/113782984/499f0c83-27a1-446d-beb1-cce7f9a80ee4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anjali29singh** [comment]
@AmanSingh6574  can you  specify how can i produce same issue
