### ISSUE TITLE
Docs: Add a Contributors Section

### ISSUE THREAD

**Issue by SurajPratap10** [SurajPratap10/Imagine_AI#36]
**Is your feature request related to a problem? Please describe.**
- Add a contributors section in the `Readme` file

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

- Demo Pic
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/aec76fec-26b1-46dc-b936-bf69de752840)

**Comment by Mansi1236** [comment]
I'd like to work on this issue under GSSoc'23, please assign it to me

**Comment by SurajPratap10** [comment]
Assigning it to you @Mansi1236 📌
