### ISSUE TITLE
[style]: Footer UI Hover Effect error

### ISSUE THREAD

**Issue by AmanSingh6574** [SurajPratap10/Imagine_AI#360]
### What's the style idea?

an unnecessary underline is coming on hover to the email 

@SurajPratap10 pls assign me this under GSSOC23

### Add screenshots

![image](https://github.com/SurajPratap10/Imagine_AI/assets/113782984/477a7cc5-c08d-4769-ae2d-e856cf7ab946)
![image](https://github.com/SurajPratap10/Imagine_AI/assets/113782984/d9f0390e-1519-4ae8-afb5-6e977b8c8b16)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
Raise a new issue after completing the previous one, As it's not a good practice to assign so many issues to a single folks at a time. For now I am closing this @AmanSingh6574 👍

**Comment by AmanSingh6574** [comment]
@SurajPratap10  sir can you pls open this issue now as the rest of the issues are completed
