### ISSUE TITLE
Make the ABOUT section text responsive

### ISSUE THREAD

**Issue by SurajPratap10** [SurajPratap10/Imagine_AI#38]
**Describe the bug**
- On switching to the mobile view the responsiveness of the text in the `About` section breaks, so fix that.

**Expected behavior**

**Screenshots**
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/37b48e40-568e-47bd-acba-04ce7a0d18bd)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AhmedBedeir** [comment]
Hi @SurajPratap10 
I'll be happy to help you with this bug. under gssoc23

**Comment by AhmedBedeir** [comment]
take a look at this:
![recording-2023-05-21-12-20-59](https://github.com/SurajPratap10/Imagine_AI/assets/66643588/806cf6f0-cef3-4fae-b27b-2d2ac60e643b)

**Comment by AhmedBedeir** [comment]
can you assign me this issue under GSsoc'23
