### ISSUE TITLE
[style]: User feedback icons position

### ISSUE THREAD

**Issue by Atharvashirsh** [SurajPratap10/Imagine_AI#384]
### What's the style idea?

We need to improve the Social media Icon Links in the User Feedback section. These icons should be aligned in the center which will look more symmetrical.

### Add screenshots

![Screenshot (155)](https://github.com/SurajPratap10/Imagine_AI/assets/121449422/48cbbeb8-5c0e-40c7-8d10-a70ad4b64d66)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tayyab-ilyas** [comment]
I can fix this

**Comment by Atharvashirsh** [comment]
@SurajPratap10 Can you please also add `gssoc23` label to this issue? 
I'm a GSSoC'23 contributor.
