### ISSUE TITLE
Revealing Animation On scrool

### ISSUE THREAD

**Issue by lakhan06** [SurajPratap10/Imagine_AI#389]
**Is your feature request related to a problem? Please describe.**
My feature is requested to improve user experience

**Describe the solution you'd like**

I want to add revealing animation effect in which headings and cards or images come with a revealing animation effect on scrolling

**Describe alternatives you've considered**
effects like parallax effect can also be added in the image of hero section

**Additional context**
@SurajPratap10 I am writing to kindly request your attention and consideration in reviewing and accepting issue. I would greatly appreciate it if you could allocate some time to review the issue and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly

**Comment by lakhan06** [comment]
hi @SurajPratap10  I request you to label the issue with gssoc and level tag so that this issue can be consider under gssoc and can 
get points out of it
Thankyou

**Comment by SurajPratap10** [comment]
Labels are only needed on the PRs

**Comment by lakhan06** [comment]
> Labels are only needed on the PRs

ok @SurajPratap10 But thank you for considering my request means a lot
