### ISSUE TITLE
Landing Page : Content Addition

### ISSUE THREAD

**Issue by astha-05** [SurajPratap10/Imagine_AI#39]
**Is your feature request related to a problem? Please describe.**
**Persuasive Description about the platform**

**Describe the solution you'd like**
Some content can be added in the landing page. Like catchy introduction about your platform can be added. For example **IMAGINE AI : Ignite Innovations using AI** 
Many more catchy phrases can be added so that platform appears more appealing to the user.

**Describe alternatives you've considered**
Overall appearance of the landing can also be changed. 

@SurajPratap10 Please assign this issue to me under GSSOC'23 as I have experience in designing and content writing.

**Comment by SurajPratap10** [comment]
Are you working on it? @astha-05

**Comment by astha-05** [comment]
Yes @SurajPratap10 I'm working on it. I'll finish it by sunday.

**Comment by PoulavBhowmick03** [comment]
Hey @SurajPratap10 Can it be assigned to me? It's been 3 weeks but hasn't been done yet
