### ISSUE TITLE
Bottom to top scrooll button

### ISSUE THREAD

**Issue by lakhan06** [SurajPratap10/Imagine_AI#390]
**Is your feature request related to a problem? Please describe.**
My feature is requested to improve user experience

**Describe the solution you'd like**
I want to add bottom to top scroll button so that user does not need to scroll by himself to top .
he just need to click on that button and he will be taken to top of page.

**Additional context**
@SurajPratap10 I am writing to kindly request your attention and consideration in reviewing and accepting issue. I would greatly appreciate it if you could allocate some time to review the issue and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly

**Comment by SurajPratap10** [comment]
Kindly, don't raise so many issues at once. At max work on 2 issues at a time. Wait for the merge then raise a new issue. So, for now I am closing this

**Comment by lakhan06** [comment]
ok @SurajPratap10  i will complete previous issues then raise this one again sorry for inconvenience
