### ISSUE TITLE
Email Application opening on clicking Email ID on the footer

### ISSUE THREAD

**Issue by chinmayjain08** [SurajPratap10/Imagine_AI#393]
**Is your feature request related to a problem? Please describe.**
An email is mentioned on the website so that if someone clicks it must open a mail application to seamlessly send a mail. That is exactly the feature I want to add.

**Describe the solution you'd like**
On clicking the email mentioned on page a mail application opens up in users device with our email id already at recieving end.

**Describe alternatives you've considered**
If not this then there is no such use of email link so we can remove it.

**Additional context**
It is important that the mail feature makes it easier for user to send mail.

**Comment by SurajPratap10** [comment]
Kinfly , don't raise so many issues at once, complete 1-2 issues then raise a new one .👍
