### ISSUE TITLE
[style]: Better layout of images and social links in Testimonial Section of About US

### ISSUE THREAD

**Issue by chinmayjain08** [SurajPratap10/Imagine_AI#395]
### What's the style idea?

We need to improve:
the layout of cards
introduce hover effects on cards 
the layout of social media buttons

### Add screenshots

![image](https://github.com/SurajPratap10/Imagine_AI/assets/92749015/6b9b87e3-f2bb-4c93-99ec-1631acb9aff9)
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92749015/07b12778-e590-4f48-9630-31a120b28b5c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ritik48** [comment]
@chinmayjain08 please assign this issue to me under gssoc23

**Comment by chinmayjain08** [comment]
Hi @SurajPratap10 , thanks for assigning.
But you haven't mentioned the level of Issue.
Actually I am contributing under the GSSOC'23 program, so the mentioned level would help me land a better rank. ✌️

**Comment by SurajPratap10** [comment]
Ya, but on discord they mentioned it that labels are considered only on PRs

**Comment by chinmayjain08** [comment]
solved in #425 with no merge conflicts.
