### ISSUE TITLE
Home Section Looks Wired

### ISSUE THREAD

**Issue by 9520prashant** [SurajPratap10/Imagine_AI#40]
In Home section there are lot of thing which we can improve. You can see in the Screen Shot that I mentioned We can simple shift the Text Section in Left part and right of the Home Section We can add an Open ApI Image or Our Own Product Image. 
Hey @SurajPratap10 I wanna work on this serious issue please assign me.

![Screenshot (234)](https://github.com/SurajPratap10/Imagine_AI/assets/99237795/354a29aa-851a-477d-8173-10235a898a7e)

**Comment by SurajPratap10** [comment]
Assigning it to you @9520prashant 📌

**Comment by syedawanya18** [comment]
I want to work on this issue
Pleasure Assign so that I can show my skills.

**Comment by SurajPratap10** [comment]
I have already assigned it to @9520prashant , so you can work on other issues @syedawanya18 or if this issue needs any further update I will assign it to you.

**Comment by syedawanya18** [comment]
for sure!

**Comment by 9520prashant** [comment]
Hey @SurajPratap10 I have created logo for Home Section I need some help can @syedawanya18 Help me.

**Comment by SurajPratap10** [comment]
> Hey @SurajPratap10 I have created logo for Home Section I need some help can @syedawanya18 Help me.

Sure reach out to her, if you both wanna collaborate

**Comment by 9520prashant** [comment]
@SurajPratap10 assign us this issue

**Comment by 9520prashant** [comment]
@SurajPratap10 assign us this issue

**Comment by 9520prashant** [comment]
@syedawanya18 let's discuss connect with me on my discord
id = prashant varma #9241

**Comment by 9520prashant** [comment]
Hey @SurajPratap10 I am working on it I have completed Navbar Designing and @Ks103 doing great in designing please assign this issue to me and her.

**Comment by SurajPratap10** [comment]
@9520prashant  this issue was assigned to you and @syedawanya18  right ?

**Comment by 9520prashant** [comment]
yep but i think @syedawanya18 is not active

**Comment by 9520prashant** [comment]
I don't have her/his socials @SurajPratap10

**Comment by SurajPratap10** [comment]
OK, so do tell the person whom you wanna work with to comment here then only I can assign him/her @9520prashant

**Comment by 9520prashant** [comment]
Assign this issue to me and @Ks103 She is very good in designing

**Comment by 9520prashant** [comment]
Hey @SurajPratap10 I don't able to see my feature in sign up page as well as in navbar How??

**Comment by SurajPratap10** [comment]
> Hey @SurajPratap10 I don't able to see my feature in sign up page as well as in navbar How??

Probably someone's PR might have overshadowed it  , but can you precisely elaborate on your feature which is not showing?

**Comment by 9520prashant** [comment]
> 

Hey @SurajPratap10 this is the [Navbar](https://www.figma.com/file/a8pdJhaVBV13EQZtRTovod/Untitled?type=design&node-id=1%3A2&t=oY9nY1kscoQC99FJ-1) design which I have developed
