### ISSUE TITLE
Footer needs improvement in dark mode

### ISSUE THREAD

**Issue by gayatriagarwal19** [SurajPratap10/Imagine_AI#401]
**Describe the bug**
A black box appears in the subscribe us section in dark mode 

**To Reproduce**
1. Go to 'About Us'
2. Scroll down to 'Footer section'

**Expected behavior**
The background should be uniform and there should be no black box

**Screenshots**
![IMAGINE - AI - Google Chrome 22-06-2023 21_17_22](https://github.com/SurajPratap10/Imagine_AI/assets/98116507/ec070812-96c0-428d-b74c-972a4034d892)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
I would like to work on the issue, please assign it to me under Gssoc23

**Comment by gayatriagarwal19** [comment]
@SurajPratap10 Thanks for assigning me the issue, could you please add the level since I'm contributing under Gssoc23.

**Comment by SurajPratap10** [comment]
> @SurajPratap10 Thanks for assigning me the issue, could you please add the level since I'm contributing under Gssoc23.

Sure, but still ( GSSoC team only checks the labels of PRs not issues)
