### ISSUE TITLE
[style]: Text and Button On Home Page Not Aligned and Properly Spaced.

### ISSUE THREAD

**Issue by chinmayjain08** [SurajPratap10/Imagine_AI#403]
### What's the style idea?

We need to improve the text alignment  and Call to Action button on the Main Page Hero Section.
Padding and Alignment needs to be improved.

### Add screenshots

![image](https://github.com/SurajPratap10/Imagine_AI/assets/92749015/3c122230-cbc8-4870-bfe3-e41560888b0d)
As we can see the text is not aligned properly so it needs to be improved.
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92749015/aab6f437-9db7-40ba-869e-fcaf161f45b2)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mansi209aps** [comment]
Hii @chinmayjain08 , I am eager to work on this issue.

**Comment by chinmayjain08** [comment]
fixed in #425 with no merge conflicts.
