### ISSUE TITLE
Changing the color of the Logo

### ISSUE THREAD

**Issue by Suhaani07** [SurajPratap10/Imagine_AI#406]
### What's the style idea?

In the dark mode, the gray color of the logo looks too dull. We should change it to either blue tone or to a lighter shade of gray.

### Add screenshots

<img width="410" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/98284331/c0e6294b-0833-4637-b0fe-64642243c301">

Please assign me this under gssoc 2023. Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abhinavcode13** [comment]
Assign me if not done @SurajPratap10
