### ISSUE TITLE
Navbar should have a Toggle Hamburger menu

### ISSUE THREAD

**Issue by crocmons** [SurajPratap10/Imagine_AI#413]
Navbar should have a Toggle Hamburger menu icon so that we can easily see all the pages
![Screenshot (439)](https://github.com/SurajPratap10/Imagine_AI/assets/106610322/4e06e9bf-c983-4536-950e-99c8b5bed140)

**Comment by crocmons** [comment]
please add the gssoc23 label also add the level

**Comment by SurajPratap10** [comment]
> please add the gssoc23 label also add the level

As mentioned by folks on discord , labels are only checked on the PRs not on issues. Still I added them 👍

**Comment by crocmons** [comment]
@SurajPratap10 can I use tailwind css for adding this?
