### ISSUE TITLE
[style]: Improving the homepage 

### ISSUE THREAD

**Issue by ManavMalhotra** [SurajPratap10/Imagine_AI#415]
### What's the style idea?

Adding a little bit of margin and padding on the right and left can improve the user experience.

### Add screenshots

![image](https://github.com/SurajPratap10/Imagine_AI/assets/64147782/55d069a4-06c8-4eb3-917b-50feb9de48fb)

This is the prototype but redesigning the content with proper call to action will improve it 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ManavMalhotra** [comment]
![MacBook Pro 14_ - 1](https://github.com/SurajPratap10/Imagine_AI/assets/64147782/bc0e57d7-8653-4e64-82fd-747fa59ea4a5)

I have developed a prototype it will take some time to implement in on the homepage

**Comment by ManavMalhotra** [comment]
@SurajPratap10 Also In panic i deleted the forked repo 🥲🥲

**Comment by shobhitexe** [comment]
> @shobhitexe
> 
> I’ve fixed the conflicts but I still can’t see my code in the main branch. Can you explain why? I would really appreciate your help with this.

i will be merged when admin of project or maintainers approve your PR

**Comment by ManavMalhotra** [comment]
> > @shobhitexe
> > I’ve fixed the conflicts but I still can’t see my code in the main branch. Can you explain why? I would really appreciate your help with this.
> 
> i will be merged when admin of project or maintainers approve your PR

In my PR it's showing PR closed
