### ISSUE TITLE
[style]: to enhance the visibility of the login button

### ISSUE THREAD

**Issue by haaniyairam** [SurajPratap10/Imagine_AI#423]
### What's the style idea?

We need to improve  the size and add rounded corners

### Add screenshots

Add screenshots

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
Raise and issue with proper pics, description

**Comment by SurajPratap10** [comment]
> Please raise an issue with proper pics, description
