### ISSUE TITLE
[style]: Improve the FAQ section

### ISSUE THREAD

**Issue by sumitkr2000** [SurajPratap10/Imagine_AI#429]
### What's the style idea?

We need to improve the FAQ section of the website. Currently, it is not looking professional and looking like very cluttered. The color combinations used are also not user-friendly. I will create a proper faq section with toggle buttons by which users can toggle button to see the answer to the questions. Please assign me this issue. Thank you!

### Add screenshots

![image](https://github.com/SurajPratap10/Imagine_AI/assets/100675296/434270e9-54a8-46d2-ad52-1a098d3f649f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
Assigning this to you and closing your test of the issues as you have to work on one issue at a time then after merging it via a PR you should open a new issue✌

**Comment by sumitkr2000** [comment]
@SurajPratap10 Everything is looking fine in localhost. I don't know why its distorted on the live version. Have you updated the live website?

- localhost:-

![image](https://github.com/SurajPratap10/Imagine_AI/assets/100675296/bcf7803b-2f64-46d6-b160-e8eec8b1d1d0)

- live:-

![image](https://github.com/SurajPratap10/Imagine_AI/assets/100675296/4c3be742-59b7-4718-9ff2-306068821e3e)

**Comment by sumitkr2000** [comment]
All the issues that I have raised are good in the localhost version

**Comment by sumitkr2000** [comment]
@SurajPratap10 ?
