### ISSUE TITLE
[style]: Redesign the Navbar

### ISSUE THREAD

**Issue by ManavMalhotra** [SurajPratap10/Imagine_AI#433]
### What's the style idea?

We need to improve to improve the navbar to make the website look more modern. I have some idea

### Add screenshots

This is the prototype version of navbar 

![image](https://github.com/SurajPratap10/Imagine_AI/assets/64147782/3d950830-cc0e-491e-9f5d-1845bc8bf5dd)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ManavMalhotra** [comment]
Please assign this task to me I can work on this under my GSSOC'23 contribution

**Comment by SurajPratap10** [comment]
Assigning it to you, complete this issue then raise a new one✌
