### ISSUE TITLE
[style]: Change the look of Login Page

### ISSUE THREAD

**Issue by trishanu-init** [SurajPratap10/Imagine_AI#436]
### What's the style idea?

We could improve the login page by properly aligning the divs and changing the font and background.

### Add screenshots

![image](https://github.com/SurajPratap10/Imagine_AI/assets/85580785/2040eb99-7082-4368-9cf4-29cf22da221c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Abhinavcode13** [comment]
Please assign me if not done by other contributor @SurajPratap10
