### ISSUE TITLE
Home Page UI-bug 

### ISSUE THREAD

**Issue by yashpreet2707** [SurajPratap10/Imagine_AI#439]
**Describe the bug**
The home page is not looking good

**Screenshots**

<img width="1440" alt="Screenshot 2023-06-25 at 1 57 11 AM" src="https://github.com/SurajPratap10/Imagine_AI/assets/111020648/a026a796-d0a4-442f-9319-d01cb6161e02">

<img width="1440" alt="Screenshot 2023-06-25 at 1 56 57 AM" src="https://github.com/SurajPratap10/Imagine_AI/assets/111020648/b7c17f52-8696-45c4-9003-6270cfe6b143">

**Comment by yashpreet2707** [comment]
please assign me this issue under gssoc'23 contributor.

**Comment by SurajPratap10** [comment]
It's fixed now
