### ISSUE TITLE
[style]: NewsLetter Responsive issue

### ISSUE THREAD

**Issue by Aryan5464** [SurajPratap10/Imagine_AI#448]
### What's the style idea?

We need to improve the Responsiveness of the newsletter as shown in the video below the section is looking too awful.
This section needs to be corrected as a **high priority** as it is destroying the experience of all mobile users.

https://github.com/SurajPratap10/Imagine_AI/assets/111825539/ae7a1f80-7f03-4b17-ae37-504be3942f88

### Add screenshots

Add screenshots

![image](https://github.com/SurajPratap10/Imagine_AI/assets/111825539/73779dc9-e8c5-416c-8235-97b6279e3fb3)

![image](https://github.com/SurajPratap10/Imagine_AI/assets/111825539/14375ba9-762c-4f99-a2a8-f6a9303f630d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by siddarthdayala** [comment]
Hey @Aryan5464 Are you still working on this issue?
