### ISSUE TITLE
Navbar colour fixing and logo design in place of Imagine_ai text 

### ISSUE THREAD

**Issue by Urmilasc** [SurajPratap10/Imagine_AI#45]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Urmilasc** [comment]
Can, I work on this enhancement in project , please assign me this under the label of GSSoc23

**Comment by syedawanya18** [comment]
I want to work on this issue
Pleasure Assign it to so i can be better at my skills

**Comment by vk20july** [comment]
@SurajPratap10 sir i want to work on this issue under gssoc'23
