### ISSUE TITLE
[style]: Improve Contact Us form

### ISSUE THREAD

**Issue by rishuraj1** [SurajPratap10/Imagine_AI#450]
### What's the style idea?

We need to improve  the contact us form as it is not appealing and user friendly.

I propose to make it
- user friendly by adding some relevant icons
- improving styles 
- changing text properties

Please assign me this issues under GSSoC '23.
Thank You !

### Add screenshots

<img width="959" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/47839626/d0f1c3fe-5540-4c83-b9d6-28a44295ae2b">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
Many are already working on `contact` section so for now I am closing this one. You can contribute in new issues
