### ISSUE TITLE
[Feature]: Add 'Forgot Password' Option for Login Details Section

### ISSUE THREAD

**Issue by NarendraKoya999** [SurajPratap10/Imagine_AI#459]
**Is your feature request related to a problem? Please describe.**

### GSSOC'23

**Describe the solution you'd like**
- Add **`Forgot Password Feature`** in **`Login Details`** Section.
- In sometimes, User Missing **`Login Details like Mainly Password Details.`**

**Describe alternatives you've considered**

**Additional context**
- **`I want to work on this Issue. Because of, In every Login Page. Use Forgot Password Feature `**

### Screenshot
![imagineai-1](https://github.com/SurajPratap10/Imagine_AI/assets/84512164/0971312b-7696-4a36-b9e9-3a1c5a599bec)

**Comment by Saimurugeshwari** [comment]
I would like to contribute on this issue under GSSOC23
