### ISSUE TITLE
Working on the error message, if the image is not generate

### ISSUE THREAD

**Issue by Urmilasc** [SurajPratap10/Imagine_AI#46]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Urmilasc** [comment]
Hello Suraj Pratap, can i work on this issue first off all try to find what the backend problem is happenning , if not any backend problem than work on the UI of error message or do some sort of console log where actually the error is happening and help the user to right it and again try to generate image

**Comment by SurajPratap10** [comment]
2 guys are working on this issue, I will assign it to you if they can't complete it. For now, I am closing this issue.

**Comment by Urmilasc** [comment]
Okay !! Noo, Problem
