### ISSUE TITLE
 Correcting the error in Dark Mode Button

### ISSUE THREAD

**Issue by lakhan06** [SurajPratap10/Imagine_AI#476]
**Is your feature request related to a problem? Please describe.**
The Dark Mode Button is not working Properly in every page.

**Describe the solution you'd like**

The dark mode button is currently experiencing functionality issues, which not only hinder the user experience but also suffer from poor alignment. I am dedicated to rectifying these errors promptly, ensuring optimal functionality and enhancing the overall user interface for the dark mode feature..

https://github.com/SurajPratap10/Imagine_AI/assets/119161467/a8b18c2e-105b-45b4-a41c-d00c16b57136

**Describe alternatives you've considered**
 I can give it a better look and alignment

**Additional context**

@SurajPratap10 I am writing to kindly request your attention and consideration in reviewing and accepting issue. I would greatly appreciate it if you could allocate some time to review the issue and provide your feedback. If there are any areas that require further attention or modifications, please let me know, and I will be more than willing to address them promptly

**Comment by Saimurugeshwari** [comment]
I would like to work on this kindly assign this to me
