### ISSUE TITLE
Button alignment issue 

### ISSUE THREAD

**Issue by PR1YAM9** [SurajPratap10/Imagine_AI#48]
Hey @SurajPratap10 , 
I have found a small alignment issue on the landing page.
**ISSUE reference: **
Issue 1.

https://github.com/SurajPratap10/Imagine_AI/assets/92604300/5b0a61c0-24a3-4d45-8eac-89499ac0e04d

As you can see the try it button is out of alignment and is also out of the viewport when the site is accessed 
<img width="960" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/92604300/1c8c6645-19bc-461d-9aaa-bd54c6dca757">
Issue 2. 
<img width="950" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/92604300/09892422-cdd5-445e-b185-3874ceab696a">
as you can see the Generate button is too far down from the form 
### **Solution:**
1. I will fix the alignment with respect to the section above and below the button.
2. Add a smooth scroll for the button for a better user experience.
3. I will fix the alignment of the generate button.

Please assign me this issue under GGSOC 23' 
Regards Priyam Maini.

**Comment by SurajPratap10** [comment]
Can you check the live site now @PR1YAM9 , Ig it's already fixed

**Comment by PR1YAM9** [comment]
> Can you check the live site now @PR1YAM9 , Ig it's already fixed
I have checked just now it is Not fixed.
