### ISSUE TITLE
[Bug and request for enhancment] : Signup button and request for signin card enhancment

### ISSUE THREAD

**Issue by Bhuvanchand26** [SurajPratap10/Imagine_AI#481]
**Is your feature request related to a problem? Please describe.**
Actually Yes, the sign-in page' element's alignment is not proper, ***No account? signup*** goes onto the footer, and now that part looks like the heading of the header

**Describe the solution you'd like**
I want to make a better sign-in card. The "Sign in" heading is very near to the header and the "show password" button isn't aligned properly this button can be inserted just inside the password field and proper changes can be made.

**Describe alternatives you've considered**
the simple alternative is to just move the signup button a bit up.

![image](https://github.com/SurajPratap10/Imagine_AI/assets/131843589/60817301-b056-4cfd-8207-3ac64edb4de5)

Under gssoc'23 assign me this issue.I'll make a clean signin card.

**Comment by SurajPratap10** [comment]
This has been assigned to another person earlier, so you can contribute via raising new issues

**Comment by Bhuvanchand26** [comment]
Hey @SurajPratap10, Just gone through issues the peroson was trying to make password visibility toggle button, I want to make the Sign in as a card and make proper alignments to it. More like 
![image](https://github.com/SurajPratap10/Imagine_AI/assets/131843589/e1b4ad0b-eef4-4c43-be57-0562aaa0f345)
