### ISSUE TITLE
[style]: Navbar needs Improvement 😨❗

### ISSUE THREAD

**Issue by chinmayjain08** [SurajPratap10/Imagine_AI#487]
### What's the style idea?

We need to improve the layout and styling of navbar to the earliest as it is a very crucial section of website.
The User Interface of a website depends very much on the navbar. Also it is very important to improve the layout of the navbar as it looks very unorganised.

### Add screenshots

![image](https://github.com/SurajPratap10/Imagine_AI/assets/92749015/e8417d88-fd34-4253-b0c6-1681acee48fb)
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92749015/0ebbe2bc-c37f-45be-b580-735d770e41c8)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
Go ahead, I also looked now that it's broken.

Due to so many PRs , Issues the project is getting ( it's good ) reason why things break and conflicts keep arising.

As soon as you finish this raise a PR and leave a message in Discord 👍

**Comment by chinmayjain08** [comment]
I will message you here, will it be okay ?

**Comment by chinmayjain08** [comment]
Solved in #489 having NO merge conflicts.

**Comment by SurajPratap10** [comment]
You need to correct that as it remains the same, as you can see on the deployed site after I merged your PR
