### ISSUE TITLE
Year in footer section is static

### ISSUE THREAD

**Issue by OMKAR-KALEPU** [SurajPratap10/Imagine_AI#491]
**Describe the bug**
The year in footer is set static. It shows 2020.

**Expected behavior**
The date should be dynamic.

**Screenshots**
![image](https://github.com/SurajPratap10/Imagine_AI/assets/83866602/8a3cf959-1f9e-4f0f-97ae-960f47810a1c)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [Chrome]

**Comment by Saimurugeshwari** [comment]
I would like to contribute for this issue, Kindly assign this to me
