### ISSUE TITLE
[style]: The home page seems broken

### ISSUE THREAD

**Issue by OMKAR-KALEPU** [SurajPratap10/Imagine_AI#492]
### What's the style idea?

We need to improve Home Page

### Add screenshots

![image](https://github.com/SurajPratap10/Imagine_AI/assets/83866602/34e65841-444c-4522-8962-ff17bd7e6c17)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Saimurugeshwari** [comment]
I would like to work on this issue, Kindly assign it to me
