### ISSUE TITLE
changes in font style and  enter text  container

### ISSUE THREAD

**Issue by sandeep0009** [SurajPratap10/Imagine_AI#5]
i want to change the font style and also color of font should be changed when hovering over it and also while hovering over image ai text cursore should not be there insted an pointer should be there.
second thing the text box should not contain courser pointer while typing in the box of the enter text.
please give me the chance to make all these changes

**Comment by SurajPratap10** [comment]
Assigned to you @sandeep0009

**Comment by syedawanya18** [comment]
I want to work on this issue as a contributor.
Pleasure Assign so that I can show my skills under GSSoC'23.

**Comment by SurajPratap10** [comment]
@sandeep0009  if u are not free then I can assign it to @syedawanya18 , plz reply..

**Comment by sandeep0009** [comment]
> @sandeep0009 if u are not free then I can assign it to @syedawanya18 , plz reply..

I'm free and I'm working on it u will have it by end of this day!! And sorry for delay just finishing with it and will be sending it by end of the day

**Comment by SurajPratap10** [comment]
> > @sandeep0009 if u are not free then I can assign it to @syedawanya18 , plz reply..
> 
> I'm free and I'm working on it u will have it by end of this day!! And sorry for delay just finishing with it and will be sending it by end of the day

Ok, No problem take your time. @syedawanya18  as u can see he is already working on this issue so you can raise or wait for new issues.

**Comment by SurajPratap10** [comment]
> > @sandeep0009 if u are not free then I can assign it to @syedawanya18 , plz reply..
> 
> I'm free and I'm working on it u will have it by end of this day!! And sorry for delay just finishing with it and will be sending it by end of the day

Whatever update you do just keep it in track with the live website as it is updating constantly by the PRs of other folks

**Comment by syedawanya18** [comment]
for sure, i can wait
