### ISSUE TITLE
Alignment and Overlapping of Buttons

### ISSUE THREAD

**Issue by premsaivarmachekuri** [SurajPratap10/Imagine_AI#50]
Hi @SurajPratap10,  I wanted to bring an issue to your attention regarding the alignment and overlapping of buttons on the [Webpage.](https://imagine-ai-17zf.vercel.app/)

**Description:**
* I would like to raise an issue regarding the alignment and overlapping of buttons on the webpage. This issue is impacting the user experience, particularly on tablet and desktop devices. I believe addressing this problem will greatly enhance the usability of the platform.

**Problem:**
The current alignment of the "Try It" and "Generate" buttons is not visually appealing and can confuse users. Specifically, the "Try It" button is overlapping with the image description section on tablet and desktop devices, which hampers user interaction. Additionally, the "Generate" button within the image description section has excessive vertical spacing, which negatively affects the overall aesthetics of the page.

**Proposed Solution:**
To improve the alignment and usability of the buttons, I suggest implementing the following solutions:

* Adjust the alignment of the "Try It" and "Generate" buttons to ensure they are visually separated and positioned correctly within their respective sections.
* Fix the overlapping issue by ensuring that the "Try It" button does not overlap with the image description section on tablet and desktop devices.
* Reduce the excessive spacing above and below the "Generate" button in the image description section, achieving a more compact and visually balanced layout.

**Alternative Considerations:**
While the proposed solutions should address the alignment and overlapping issues effectively, alternative approaches could be considered. These may include:

* Adjusting button sizes: Evaluate the size of the buttons to ensure they are proportionate to the surrounding elements. Enlarging the buttons slightly or reducing their size can help achieve better alignment and spacing within the page layout.

* Optimizing button placement for different devices: Consider responsive design techniques to ensure the buttons are appropriately positioned on various devices. Testing the placement on different screen sizes and resolutions can help identify any issues specific to certain devices and allow for adjustments accordingly.

**Additional Context:**
Mobile
![image](https://github.com/SurajPratap10/Imagine_AI/assets/110842297/40fe7224-db0d-4340-bde8-dfe0834f82ac)
Tablets and Desktops
![image](https://github.com/SurajPratap10/Imagine_AI/assets/110842297/2bc4b28c-fe6d-4569-a250-8e698c9953ad)
![image](https://github.com/SurajPratap10/Imagine_AI/assets/110842297/2381192f-661b-4c0d-976f-45c00ec2daec)

I am participating in GSSOC 23 and have previous experience in resolving similar issues related to UI/UX improvements. With my expertise, I am confident in my ability to tackle this issue effectively and contribute.

Regards,
Premsai Varma

**Comment by SurajPratap10** [comment]
I am not facing these issues , check the website again https://imagine-ai-17zf.vercel.app/
