### ISSUE TITLE
[style]: fixing navbar

### ISSUE THREAD

**Issue by shobhitexe** [SurajPratap10/Imagine_AI#500]
### What's the style idea?

As seen in below SS theres a big gap between navlinks and the switch theme button is not aligened well

### Add screenshots

![image](https://github.com/SurajPratap10/Imagine_AI/assets/29349136/6801617f-e4c6-4e2a-aa61-2dc15c6cd5eb)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
Keep in mind of the responsivness while doing this @shobhitexe  👍
