### ISSUE TITLE
Error in the navbar 

### ISSUE THREAD

**Issue by lakhan06** [SurajPratap10/Imagine_AI#507]
**Is your feature request related to a problem? Please describe.**
navbar not working correctly .there is some error. I can try to  solve it  under 30 min so that it did not bother other contributors

**Describe the solution you'd like**
To enhance the user experience and resolve the issue with the malfunctioning navbar, it is necessary to make changes to the CSS code. By addressing the error, we can ensure that the navbar functions correctly and provides a seamless navigation experience for users.

https://github.com/SurajPratap10/Imagine_AI/assets/119161467/6bbbe174-e9b5-4728-84fb-639cd72604b5

**Describe alternatives you've considered**
Also can make it responsive.
**Additional context**
@SurajPratap10 assign me this issue i will solve it in under 30 min so that the issue did not bother other contributors in there contributions.

**Comment by SurajPratap10** [comment]
On my end it works, this happens sometimes in browsers
