### ISSUE TITLE
problem with the footer icons

### ISSUE THREAD

**Issue by Ashasindhu** [SurajPratap10/Imagine_AI#512]
**Describe the bug**
Currently, the twitter icon and youtube icon are not redirecting twitter and youtube respectively.Instead they are redirecting to facebook and instagram.so,changing the icons would solve the issue.
**To Reproduce**

1. Go to footer 
2. Click on twitter icon and youtube icon. you will find they are redirecting to facebook and instagram.
3. See error

**Expected behavior**
Changing twitter icon to facebook icon and youtube icon to instagram icon fixes this issue.
**Screenshots**
![WhatsApp Image 2023-06-28 at 23 11 47](https://github.com/SurajPratap10/Imagine_AI/assets/97841424/a47a6036-5b0b-48d6-a724-7005cd973261)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device:Redmi [e.g. iPhone6]
- Browser:chrome [e.g. stock browser, safari]

**Additional context**

**Comment by SurajPratap10** [comment]
What ss have u put?

**Comment by SurajPratap10** [comment]
> Sorry @SurajPratap10 ,I didn't get it. You mean os?

What you have added the pic of my `FB` on the issue's `screenshot` section ( context?) , there you should display the issue-related pics
