### ISSUE TITLE
Add Voice Assistant Option for DALL·E 2 Prompts

### ISSUE THREAD

**Issue by Nishitbaria** [SurajPratap10/Imagine_AI#516]
**Functional Requirements:**
1. Integration of a speech recognition library or service to capture and convert voice input to text.
2. Implementation of a voice assistant module that prompts the user for voice input and retrieves the converted text prompts.
3. Integration of the voice assistant with the existing functionality of the Imagine AI project to generate DALL·E 2 images based on the voice prompts.

**Benefits:**
- Enhanced User Experience: The voice assistant option would provide users with a convenient and intuitive way to interact with the Imagine AI project by accepting voice input for generating DALL·E 2 prompts.
- Accessibility: Users with limited typing capabilities or visual impairments would benefit from the voice assistant option, as it would enable them to easily generate prompts using their voice.
- Increased Flexibility: The addition of voice input expands the range of input modalities available, catering to different user preferences and needs.

**Implementation Considerations:**
- Selection of an appropriate speech recognition library or service that supports the required languages and has good accuracy.
- Integration of the voice assistant module into the existing project architecture, ensuring compatibility and seamless interaction with the DALL·E 2 generation process.

@SurajPratap10  ,Please assign me this issue ,I will implement this voice assistant in a day

**Comment by Nishitbaria** [comment]
@SurajPratap10  Please assign me this issue,I will implement this voice assistant and create pull request in a day

**Comment by Saimurugeshwari** [comment]
i would like to contribute, Kindly assign this to me

**Comment by Nishitbaria** [comment]
@Saimurugeshwari I am working on it

**Comment by Nishitbaria** [comment]
@SurajPratap10  I have made voice assistant and will create pr today

**Comment by Nishitbaria** [comment]
@SurajPratap10  please merge pull request,I have added an awesome voice assistant please see video
