### ISSUE TITLE
Icon not visible

### ISSUE THREAD

**Issue by shraddha761** [SurajPratap10/Imagine_AI#517]
**Describe the bug**
Because of animation of page icons are not visible properly and able to even sign up
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/SurajPratap10/Imagine_AI/assets/106100728/eb2c7eef-22d6-4c0a-9c30-01b93e5bbf7e)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Assign this issue to me under GSSOC'23

**Comment by SurajPratap10** [comment]
Assigned already
