### ISSUE TITLE
Error in sign in page

### ISSUE THREAD

**Issue by lakhan06** [SurajPratap10/Imagine_AI#518]
**Is your feature request related to a problem? Please describe.**
There is an error in sign in page..
![image](https://github.com/SurajPratap10/Imagine_AI/assets/119161467/77e42479-292b-4333-ba41-bbbbe4869b55)

**Describe the solution you'd like**

There appears to be an error on the sign-in page, as the content seems to be scattered randomly, resulting in a suboptimal user experience. It is crucial to address this issue and enhance the statement for better understanding. Here's an improved version:

"The sign-in page is currently experiencing display issues, with the content appearing disorganized and scattered throughout the interface. This situation significantly hampers the user experience, making it challenging for individuals to navigate and interact with the page effectively. Resolving this problem promptly is essential to ensure a seamless and intuitive sign-in process for our users."
**Describe alternatives you've considered**
Ui can also be improve

**Additional context**
@SurajPratap10 Please assign me this issue so that i can work fast on it and solve the problem.

**Comment by lakhan06** [comment]
@SurajPratap10 Please assign me this issue so that i can work fast on it and solve the problem.

**Comment by ADRathod1614** [comment]
Please assign me this issue so that i can solve the problem.

**Comment by SurajPratap10** [comment]
> Please assign me this issue so that i can solve the problem.

You can collaborate if @lakhan06  permits as this issue is raised by him only

**Comment by ADRathod1614** [comment]
@lakhan06 do you need any assistance ,I have all knowledge of login functionalities .if yes please grant me permission.
