### ISSUE TITLE
Feature: Adding new SECTIONS to the Website

### ISSUE THREAD

**Issue by SurajPratap10** [SurajPratap10/Imagine_AI#53]
**Is your feature request related to a problem? Please describe.**
- Add some new sections to the website
- Make the accessible through the Navbar

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
*You are free to drop your ideas on what `sections` you want to add in the website, just after adding them show me some demo pics or videos*.

**Comment by sandeep0009** [comment]
How to use section? in this we can make the user understand how they can use this and also can tell them what are the functionality of suprise me and generate and basically also we can also help user how to go with the website .this will help them to go the website easily and also you are having a section where you said "get you open ai key" so most users may find difficulty to how to go to that site or how to generate key .through a help section we can make them navigate through that

**Comment by SurajPratap10** [comment]
assigned @sandeep0009 📌

**Comment by sandeep0009** [comment]
<img width="805" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/63727946/7d8a13b3-fb38-4b62-903f-6956ef4bee8c">
just i want ask u that should i made How to use section below or after this?any suggestions u wana give

**Comment by SurajPratap10** [comment]
Ya, you can make that section or FAQ etc @sandeep0009

**Comment by sandeep0009** [comment]
faq will be better idea will start working on it
