### ISSUE TITLE
[style]: footer section

### ISSUE THREAD

**Issue by linga66** [SurajPratap10/Imagine_AI#536]
### What's the style idea?

The footer height is too much 
We can decrease the the height of the footer and make page look attractive 

### Add screenshots

![Screenshot (812)](https://github.com/SurajPratap10/Imagine_AI/assets/103192975/56de4a12-6e23-4520-b1e6-c59847cffa9b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jyoti145** [comment]
I want to work on this issue please assign
