### ISSUE TITLE
first section spacing 

### ISSUE THREAD

**Issue by laibaahsan27** [SurajPratap10/Imagine_AI#54]
**Describe the bug**
The spacing in this section in not symmetric. The section is not covering the whole screen, as you can see the next section which is of black colour while you are on the first section. The text is too spread out which is leaving empty space below the "Try It" button.
the heading is in lower case with is not looking good.

**To Reproduce**
1. Go to 'your website'
3. Scroll down to '1st section just below the navbar'

**Expected behavior**
1) I will convert heading text to uppercase.
2) I will increase the section height to fit completely on the whole screen.
3) I will increase the lines for the text and vertically allign it to the center.
4) I will move the "Try It" button down to make the space look filled.

**Screenshots**
![image](https://github.com/SurajPratap10/Imagine_AI/assets/123810454/7e27d857-a393-4c1a-b0a5-7eefd57ec32c)

**Additional context**
Allow me to make the above changes and make your website look symmetric.
@SurajPratap10 please assign me this issue under the label of GSSOC 2023

Regards 
Laiba Ahsan

**Comment by SurajPratap10** [comment]
Assigning it to you @laibaahsan27 📌
