### ISSUE TITLE
Hover effect is missing in the footer content

### ISSUE THREAD

**Issue by HimanshuNarware** [SurajPratap10/Imagine_AI#541]
The hover effect is missing in the footer section content
**Describe the solution you'd like**
Hover effect and left to right underline animation
**Describe alternatives you've considered**
Improve the UI and the readability of the website.
**Additional context**
![16](https://github.com/SurajPratap10/Imagine_AI/assets/83147410/d42bde8d-ed8e-46db-8d87-5b3e04444e96)

**Comment by mraduls129** [comment]
kindly approve me , I just to want to good changes..
