### ISSUE TITLE
[style]: Login page have lots of bug and style isssues[important]

### ISSUE THREAD

**Issue by HimanshuNarware** [SurajPratap10/Imagine_AI#542]
### What's the style idea?

The login page's alignment is disturbed, and The entire UI of the login page is disturbed. This is a high priority issue. I want to work on this issue

### Add screenshots

Add screenshots
![17](https://github.com/SurajPratap10/Imagine_AI/assets/83147410/17405543-41e4-494f-aac6-dc7c26129f2c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tayyab-ilyas** [comment]
is somebody working on this issue?

**Comment by HimanshuNarware** [comment]
> is somebody working on this issue?

Yep I am working on it

**Comment by HimanshuNarware** [comment]
Yep
