### ISSUE TITLE
[style]: MockUp update

### ISSUE THREAD

**Issue by SurajPratap10** [SurajPratap10/Imagine_AI#543]
### What's the style idea?

- Update the MockUp image with a good and appealing image in the `Docs`
- Redesign a New MockUp

### Add screenshots

Add screenshots
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/3a2d6e9f-027d-4869-93e5-0fda0f0f21e5)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 0xabdulkhalid** [comment]
## Hey there @SurajPratap10, I can do it very well.

Look at the example mockups designed by me

![](https://raw.githubusercontent.com/0xabdulkhalid/tic-tac-toe/main/design/cover.webp) 

Or like these ones,

| Desktop        |
| :-------------: |
| <img src='https://raw.githubusercontent.com/0xabdulkhalid/tic-tac-toe/main/design/desktop-preview.png' alt='desktop preview'>    |

| Tablet | Mobile |
| :-----: | :-----: |
| <img src='https://raw.githubusercontent.com/0xabdulkhalid/tic-tac-toe/main/design/tablet-preview.png' width='580px' alt='tablet preview'> | <img src='https://raw.githubusercontent.com/0xabdulkhalid/tic-tac-toe/main/design/mobile-preview.png' alt='mobile preview'> |


## Please assign this issue to me, to make the work done!

**Comment by 0xabdulkhalid** [comment]
I'm a experienced Figma user, So i can able to make high quality mockups and also can optimize the image to `webp` for providing Next-Gen images to the Web 🚀

**Comment by SurajPratap10** [comment]
Great

**Comment by 0xabdulkhalid** [comment]
Hi there @SurajPratap10 ,

I have created two different variants of Mockup, let me know your thoughts regarding this.

Which Mockup can be selected on the above ?

PS: Don't care about the White Background for now, we can get rid of on final design.

|DESIGN ONE| DESIGN TWO|
|:--:|:---:|
|![image](https://media.discordapp.net/attachments/1130675239592923257/1130676204630966363/Variant-1.png?width=865&height=411) | ![image](https://media.discordapp.net/attachments/1130675239592923257/1130676205205606491/Variant-2.png?width=865&height=411) |

Let me know your thoughts to complete this work!

**Comment by 0xabdulkhalid** [comment]
Please share your thoughts @SurajPratap10, already it's too late.

**Comment by 0xabdulkhalid** [comment]
### @SurajPratap10 I asked you about which one we can use ?

|DESIGN ONE| DESIGN TWO|
|:--:|:---:|
|![image](https://media.discordapp.net/attachments/1130675239592923257/1130676204630966363/Variant-1.png?width=865&height=411) | ![image](https://media.discordapp.net/attachments/1130675239592923257/1130676205205606491/Variant-2.png?width=865&height=411) |


PS: Don't care about the White Background for now, we can get rid of on final design.



Let me know your thoughts to complete this work!
