### ISSUE TITLE
[style]: Want to Improve Imagin-AI Page and also spelling errors and aligning issues

### ISSUE THREAD

**Issue by killerraj369** [SurajPratap10/Imagine_AI#547]
### What's the style idea?

We need to improve the Improve AI Page. There are some issues in this page.

### Add screenshots

Add screenshots

![WhatsApp Image 2023-07-06 at 5 26 20 PM](https://github.com/SurajPratap10/Imagine_AI/assets/87773889/1c254490-4e5c-4dac-842b-dd87a9cfc04a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Saimurugeshwari** [comment]
Can I work on this under GSSOC 2023

**Comment by killerraj369** [comment]
Hi, @SurajPratap10 Please assign me this issue. I want to work on it.

**Comment by SurajPratap10** [comment]
> Can I work on this under GSSOC 2023

One who raises the issue has authority to work on it.
