### ISSUE TITLE
[style]: Coloring slider and scroll bar of the website

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [SurajPratap10/Imagine_AI#555]
### What's the style idea?

We need to improve  Scroll bar of the website
- Adding same color of as the website shows around the scroll bar
- with lightning effect
- Best user interface and hovering effect with lightning effect 
- Remove scroll bar after every remove of the cursor of the mouse

### Add screenshots

Add screenshots

![image](https://github.com/SurajPratap10/Imagine_AI/assets/114330097/fcef32df-42d8-4cac-afc9-472ae7f3148b)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Avdhesh-Varshney** [comment]
@SurajPratap10 sir, please assign this task to me to contribute under GSSoC'23 program

**Comment by SurajPratap10** [comment]
Complete previous ones first
