### ISSUE TITLE
[Bug] button animations aren’t working properly 

### ISSUE THREAD

**Issue by ariaxo** [SurajPratap10/Imagine_AI#56]
The "Black Waves" animation should be opacity-locked to the pink button, but now they are floating on the btn.

**Screenshots**

![IMG_6876](https://github.com/SurajPratap10/Imagine_AI/assets/97863000/e856e1e9-1d8e-4c4c-bc4a-606fba9b2fb4)

**Desktop (please complete the following information):**
 - OS: iOS 
 - Browser: safari 
 

**Smartphone (please complete the following information):**
 - Device: iPad

**Comment by SurajPratap10** [comment]
Assigning it to you @ariaxo 📌

**Comment by vk20july** [comment]
I want to work on this issue under gssoc'23
