### ISSUE TITLE
[Enhancements] Random prompts in Surprise Me & Randomly changed bgcolor

### ISSUE THREAD

**Issue by ariaxo** [SurajPratap10/Imagine_AI#57]
**Is your feature request related to a problem? Please describe.**
i have noticed that the « surprise me « prompts was preset. Is there a way to get GPT to generate random prompts? That would make it more *surprising*
Something like this :
![IMG_6877](https://github.com/SurajPratap10/Imagine_AI/assets/97863000/67313a54-9b1a-4346-8910-0adfcd796531)

Also I wonder if it’s ok to get background coloré changed after one mouse click. (I’ve seen this feature on other sites and it would be cool for a dalle 2 site I guess)

**Comment by SurajPratap10** [comment]
Ok yo do what you wish to and show me the results. Assigning it to you @ariaxo 📌
