### ISSUE TITLE
[style]: Adding margin top in thi Imagine-ai page 

### ISSUE THREAD

**Issue by ShreyaDhiman24** [SurajPratap10/Imagine_AI#593]
### What's the style idea?

![Screenshot from 2023-07-13 18-28-49](https://github.com/SurajPratap10/Imagine_AI/assets/98320971/92fec18d-ccf7-46b0-bffc-5b4e8de28392)

Wish to work under GSSoC'23.

### Add screenshots

Add screenshots

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SurajPratap10** [comment]
First do those 2 issues that I assigned to you , I can't assign so many issues to folks at a time so I am closing the rest ones. Complete those 2  first then raise new ones 👍⭐
