### ISSUE TITLE
change in the footer section

### ISSUE THREAD

**Issue by sandeep0009** [SurajPratap10/Imagine_AI#6]
footer section is blank it should contain your website links as well as creation and copyright so please assign me this to make the changes in it

**Comment by SurajPratap10** [comment]
@sandeep0009 assigned to you 🔥

**Comment by sandeep0009** [comment]
bro can you provide me links you wana add like social media or any official twitter or anything

**Comment by SurajPratap10** [comment]
> bro can you provide me links you wana add like social media or any official twitter or anything


The links are mentioned on my GitHub profile you can check it there.
