### ISSUE TITLE
Header overlap website body content

### ISSUE THREAD

**Issue by Mansi209aps** [SurajPratap10/Imagine_AI#611]
The header overlaps the body content of the website. Please assign me this issue under GSSOC'23.

<img width="957" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/78530251/9c1d05f7-7fca-4aac-83e5-d72860fed403">

**Comment by SurajPratap10** [comment]
It breaks on chrome only ig, still assigned to you
