### ISSUE TITLE
Docs: Add MIT License

### ISSUE THREAD

**Issue by SurajPratap10** [SurajPratap10/Imagine_AI#62]
**Is your feature request related to a problem? Please describe.**
- Addition of MIT License file in the repository.
- 
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/87ab567e-bac2-4c01-b1a0-6216ffa33961)

**Comment by tayyab-ilyas** [comment]
hey @SurajPratap10 can you assign this to me ?
