### ISSUE TITLE
Footer for mobile view improvement

### ISSUE THREAD

**Issue by akanksha984** [SurajPratap10/Imagine_AI#641]
Reduce spacing in footer section for mobile view so that it looks good

![image](https://github.com/SurajPratap10/Imagine_AI/assets/97845909/c635d8e3-f07d-4c6a-8918-272c1a233a40)

**Comment by SurajPratap10** [comment]
I can't assign so many issues at once to a single folk, compelete previous issues and then raise new ones 👍
