### ISSUE TITLE
GSSOC'23 - Adding more examples of prompt

### ISSUE THREAD

**Issue by rutujp78** [SurajPratap10/Imagine_AI#7]
**Adding more example of prompts**
Adding more examples of prompt will help users to write more creative prompts
There will be a button when pressed will select a random prompt from stored prompts.
Please assign me this task.

**Comment by SurajPratap10** [comment]
@rutujp78 assigned to you 🔥

**Comment by rutujp78** [comment]
> @rutujp78 assigned to you 🔥

Task done. Can I send pull request?
