### ISSUE TITLE
Styling issue in About-Us in navbar

### ISSUE THREAD

**Issue by rutujp78** [SurajPratap10/Imagine_AI#707]
**Describe the bug**
When hover to About-Us in navbar the text is not underlined as other text.

**Expected behavior**
Hovering to About-Us should add underline.

**Screenshots**
![Screenshot (295)](https://github.com/SurajPratap10/Imagine_AI/assets/76244494/f9d15f84-0f59-481d-9686-dc083f7fc18c)

Assign this issue to me under gssoc.

**Comment by SurajPratap10** [comment]
You can check the latest site, if still you want to work on this issue then comment .
