### ISSUE TITLE
Responsiveness issue

### ISSUE THREAD

**Issue by stuti-09** [SurajPratap10/Imagine_AI#72]
Text of second paragraph is bigger than text of first paragraph in mobile view which looks wierd.

![Screenshot (179)](https://github.com/SurajPratap10/Imagine_AI/assets/93007935/0a3fb46b-4c5c-4d44-a427-ec7e5436d2b4)
Please assign me this issue under gssoc'23.

**Comment by SurajPratap10** [comment]
assigned @stuti-09 📌
