### ISSUE TITLE
bug: elements are overlapped with each other on contact us page 🙅🏻❌ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [SurajPratap10/Imagine_AI#732]
**Describe the bug**
- The bug is about the overlapping elements found on Contact Us page.
- Due to uneven spacing and measurements the Elements are tend to be bounded each other on less amount of spacing.
- We need to resolve this issue otherwise the Contact Us page will looks bad to the users.

**To Reproduce**

1. Go to 'Imagine AI Contact US Page'
3. Scroll down to 'Form'

**Expected behavior**
- The elements needs to be perfectly aligned without any overlapping problems

**Screenshots**
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/6966059a-3f41-4100-964d-3401f52a98bc)

**Desktop**

- OS: ArchCraft
- Browser: Firefox
- Version: 114.54

**Comment by 0xabdulkhalid** [comment]
Hey there @SurajPratap10 👋🏻 

Please make sure to assign this issue to me to make the work done, Thank you!

**Comment by SurajPratap10** [comment]
already assigned to someone
