### ISSUE TITLE
Update HeroSection Image ✨

### ISSUE THREAD

**Issue by Nishitbaria** [SurajPratap10/Imagine_AI#744]
### Issue Description

**Current Image:** The HeroSection image on the website is outdated and needs to be replaced with a more relevant and eye-catching image.

![image](https://github.com/SurajPratap10/Imagine_AI/assets/85815172/19f37274-03da-40c4-bc34-048dcb9e02e3)

**Proposed Image:** We suggest using a high-resolution image that aligns better with the website's theme and content. The new image should reflect the essence of our project and grab the visitors' attention right away.

![image](https://github.com/SurajPratap10/Imagine_AI/assets/85815172/1894a956-c2da-4594-849e-a60e340b7ca9)

**Importance:** HeroSection is the first thing users see when they visit our website, making it a crucial element for creating a strong first impression. By updating the image, we can enhance the overall visual appeal and potentially increase user engagement.

**Comment by Nishitbaria** [comment]
Hey @SurajPratap10  Please assign me this issue

**Comment by SurajPratap10** [comment]
While raising the PR , just share the pics with 2-3 options of `images` I will tell which one to put👍
