### ISSUE TITLE
[DOCS]: <Add content and rearranging the order>

### ISSUE THREAD

**Issue by Enhancer18** [SurajPratap10/Imagine_AI#746]
### Issue Description

There is no order and structure of the contents and there are no proper screenshots.

### Proposed Solution (optional)

I would like to add a table of content, make the description of the project more attractive , make the readme more accessible and structured, and add a few images .

### Checklist

- [X] I have checked the existing [issues](https://github.com/SurajPratap10/Imagine_AI/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/SurajPratap10/Imagine_AI/blob/main/CONTRIBUTING_GUIDELINES.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by SurajPratap10** [comment]
can you elucidate further or share some pics of the enhancements you wanna do @Enhancer18
