### ISSUE TITLE
Make the LOGIN page functional

### ISSUE THREAD

**Issue by SurajPratap10** [SurajPratap10/Imagine_AI#75]
**Is your feature request related to a problem? Please describe.**
- Add functionality to the Login Page
- User can SignIn and SignUp to the website

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92919173/6d2ed3da-1761-4740-896e-3fd17fafafca)

**Comment by SurajPratap10** [comment]
Assigned @Shounmay 📌

**Comment by AKsHaT123456A** [comment]
Hey, @SurajPratap10  can you assign me this issue?

### SOLUTION APPROACH
Adding regex and navigation from frontend and connecting it with backend for double verification
**ALTERNATIVES**
Adding sign in with google facility for the user

**Comment by SurajPratap10** [comment]
@Shounmay  is already working on it
