### ISSUE TITLE
want to remove the bottom scroll bar

### ISSUE THREAD

**Issue by Sushilverma002** [SurajPratap10/Imagine_AI#750]
**Describe the bug**
want to remove the bottom scroll bar
**To Reproduce**

**Expected behavior**

**Screenshots**

https://github.com/SurajPratap10/Imagine_AI/assets/114687502/9cef635c-6972-4bbf-8d7f-29810489e410

**Desktop (please complete the following information):**

- OS: [windows]
- Browser [chrome]
- Version [ 115.0.5790.171]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by SurajPratap10** [comment]
First complete the previous issues ,the raise this one again
