### ISSUE TITLE
[DOCS]: MAKE GSSOC BANNER HD AND ADAPTIVE TO LIGHT/DARK GITHUB MODE 🌞/🌚 💡  

### ISSUE THREAD

**Issue by 0xabdulkhalid** [SurajPratap10/Imagine_AI#753]
### Issue Description

- The current state of GSSOC Banner is very poor in quality, So it looks very small for Desktop like devices.
- The image is not also dynamic so during switching Light/Dark Mode the GSSOC Banner remains as the same without any changes this make the documentation harder to read.

### Screenshots or Examples (if applicable)

| CURRENT - LIGHT THEME | CURRENT - DARK THEME |
|  :-----:   | :-----:  |
| ![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/0fd9cce1-c4dd-4e87-b64f-b19dcd1795ed) | ![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/e2cc4f0b-7de3-4624-ac30-2788ec1ee5f4) |

| DESIRED - LIGHT THEME | DESIRED - DARK THEME |
|  :-----:   | :-----:  |
| ![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/12eb6dc0-e046-40b2-a10a-2158e3542cfb)| ![](https://user-images.githubusercontent.com/63473496/213306279-338f7ce9-9a9f-4427-8c2a-3e344874498f.png) 

### Checklist

- [X] I have checked the existing [issues](https://github.com/SurajPratap10/Imagine_AI/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/SurajPratap10/Imagine_AI/blob/main/CONTRIBUTING_GUIDELINES.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

**Comment by 0xabdulkhalid** [comment]
Hey there @SurajPratap10 👋🏻 

Please make sure to assign this issue to me to make the work done, Thank You!

**Comment by SurajPratap10** [comment]
First complete the previous PRs, then text me to assign this issue to you 👍
