### ISSUE TITLE
feat: improve hero section image 🪄✨ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [SurajPratap10/Imagine_AI#779]
## Description
- Currently the hero section image is on `png` format, The important thing is that the image can't be dynamically scale like `svg` images.
- Due to this reason the hero image is looks blurred like image on my laptop screen, You can also check this by visiting Imagine AI Homepage on you Desktop/Laptop.
- My proposal to this problem is replacing the `png` hero image into `svg` based image.
- The main advantage of using `svg` image is that it can be upscaled or downscaled easily, there will no quality drops on the image. Because the whole image itself is coded on svg.
- We can add AI Related images, which will look more professional look for Imagine AI Website.

## Screenshot
![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/16f558ec-1620-458e-9f54-94641e783753)

## Images we can add

<div align=center>

![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/dc7b0f80-24ce-4636-831f-5e63967392b1)![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/3820fd82-806d-4cc9-a580-f3c3caaf1f39)![image](https://github.com/SurajPratap10/Imagine_AI/assets/92252895/589a800d-87ff-4381-9faf-513f64c48df4)

[CHOOSE ANY IMAGE ON ABOVE TO PROCEED]

</div>

**Comment by 0xabdulkhalid** [comment]
Hey there @SurajPratap10 👋🏻 

Please make sure to assign this issue to me to make the work done, Thank You!

**Comment by SurajPratap10** [comment]
`1` and `2` both look good, but I prefer 1
