### ISSUE TITLE
UI improvement of the section

### ISSUE THREAD

**Issue by Suhaani07** [SurajPratap10/Imagine_AI#78]
<img width="1054" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/98284331/96980235-111a-4197-8be1-cf4bd7fa7270">

Font should be improved as well as margin and padding should be adjusted for better visuals.

If possible, please assign me this under gssoc 2023

**Comment by SurajPratap10** [comment]
I have assigned this already to other folks so I am closing this issue now @Suhaani07
