### ISSUE TITLE
enhance dark mode 

### ISSUE THREAD

**Issue by gaur15** [SurajPratap10/Imagine_AI#82]
**Is your feature request related to a problem? Please describe.** dark mode reduces eye strain and improves readability 

**Describe the solution you'd like** Many users uses dark mode because it provides comfort of use at night or in dark environments. Dark mode can save energy consumption on devices and reduce eye strain 

**Describe alternatives you've considered**

**Additional context**

**Comment by SurajPratap10** [comment]
Go ahead @gaur15 📌

**Comment by gaur15** [comment]
Sorry sir I  was late in my pr but now my issue of enhancing dark mode is done in website. Now can I change toggle button between the two to make it look good
