### ISSUE TITLE
Adding custom arrow for selection of size of image

### ISSUE THREAD

**Issue by rutujp78** [SurajPratap10/Imagine_AI#88]
**Is your feature request related to a problem? Please describe.**
The default arrow in select tag does not looks pleasing.

**Describe the solution you'd like**
Adding a custom arrow may look more user interactive.
![Screenshot (163)](https://github.com/SurajPratap10/Imagine_AI/assets/76244494/f072accf-30b1-4230-8970-b7436339e602)

**Comment by SurajPratap10** [comment]
assigned @rutujp78 📌
