### ISSUE TITLE
Divide the Website into various Sections

### ISSUE THREAD

**Issue by SurajPratap10** [SurajPratap10/Imagine_AI#89]
**Is your feature request related to a problem? Please describe.**
- Divide the Website into different `sections`
- Make them accessible via the `Navbar`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Joe-Mwangi** [comment]
hey can you kindly assign me this issue

**Comment by SurajPratap10** [comment]
assigning it to you @Joe-Mwangi 👍
