### ISSUE TITLE
feature: add a form field to get API key from user 

### ISSUE THREAD

**Issue by rishuraj1** [SurajPratap10/Imagine_AI#9]
In future, we might want to take API key as input from the user themselves, as open ai provides limited tokens per api key.
Adding a form field in the form and sending user's API key as one of the request parameters can solve this problems.

So, UI will look something like this: 
![Screenshot (77)](https://github.com/SurajPratap10/Imagine_AI/assets/47839626/2223c086-115a-4000-9c04-bb17a217267d)

**Comment by SurajPratap10** [comment]
Nice idea!! but for this to work, you will need to tweak the code too for it's functioning purpose.

**Comment by rishuraj1** [comment]
@SurajPratap10  yes,  we'll have to send API_KEY as one of the parametrs with other parameters like Prompt and size. 
Could you please assign me this so, that I can start working on this. 
 Since I am only capable of doing frontend work and some basic backend, I can bring this to work and then you can tweak the backend structure according to your needs

**Comment by SurajPratap10** [comment]
Ok
