### ISSUE TITLE
Redirecting to home page when clicked on Brand Name

### ISSUE THREAD

**Issue by Suhaani07** [SurajPratap10/Imagine_AI#93]
A path should be added to the Brand Name to redirect to the home page
<img width="313" alt="image" src="https://github.com/SurajPratap10/Imagine_AI/assets/98284331/ca1f8af1-b33f-4bbf-b5b1-10cc1fd482bb">
If possibel, please assign me this under gssoc 2023

**Comment by SurajPratap10** [comment]
Raise this issue once you complete the previous one.
