### ISSUE TITLE
Contact page need improvement 

### ISSUE THREAD

**Issue by 9520prashant** [SurajPratap10/Imagine_AI#99]
Hey @SurajPratap10 Look at this. it needs improvement. kindly assign this issue to me so that i will start working on it ..

![Screenshot (243)](https://github.com/SurajPratap10/Imagine_AI/assets/99237795/3abf9291-5bdb-499e-8341-e28eb8b624a2)

**Comment by SurajPratap10** [comment]
assign @9520prashant  👍

**Comment by 9520prashant** [comment]
hey @SurajPratap10 i am facing somei ssue  in order to redesign the page can i know who has design it before me

**Comment by SasiVardhan247** [comment]
> Hey @SurajPratap10 Look at this. it needs improvement. kindly assign this issue to me so that i will start working on it ..
> 
> ![Screenshot (243)](https://user-images.githubusercontent.com/99237795/240338383-3abf9291-5bdb-499e-8341-e28eb8b624a2.png)

what's the issue in it @9520prashant . @SurajPratap10  there is no such issue with the contactus page upto my knowledge.
![image](https://github.com/SurajPratap10/Imagine_AI/assets/83742554/225064ee-7d67-4345-bc09-6c7949bffd40)

**Comment by SurajPratap10** [comment]
As you can see this issue is raised by @9520prashant  so I can't assign it to you as he is already assigned to it. He just needs your help so I tagged you. If you both agree I can assign you both in this issue

**Comment by SasiVardhan247** [comment]
@

> As you can see @SasiVardhan247 this issue is raised by @9520prashant so I can't assign it to you as he is already assigned to it. He just needs your help so I tagged you. If you both agree then you can collaborate and I will assign it to both of you.

I think issue is resolved @SurajPratap10 .

**Comment by SurajPratap10** [comment]
> @
> 
> > As you can see @SasiVardhan247 this issue is raised by @9520prashant so I can't assign it to you as he is already assigned to it. He just needs your help so I tagged you. If you both agree then you can collaborate and I will assign it to both of you.
> 
> I think issue is resolved @SurajPratap10 .

@9520prashant  asked for help from the user who designed the contacts page so I tagged you.

**Comment by 9520prashant** [comment]
@SasiVardhan247 I did not able to put any image in contact section.

**Comment by SasiVardhan247** [comment]
> @SasiVardhan247 I did not able to put any image in contact section.

Where do you want to put image can you exactly locate it's position like in which class or section.I' ll try to help you with solution

**Comment by 9520prashant** [comment]
in contactUs.ejs after responsive-container-block class

**Comment by SasiVardhan247** [comment]
> in contactUs.ejs after responsive-container-block class

Once check the corresponding css class properties you 'll get some idea. There won't be any issues for image adding. If you feel anything wrong try placing image below some text and check for it you will get it.One more things you can place  img in the form class

**Comment by 9520prashant** [comment]
Sure I was thinking to add a image but it's fine
